Repository BeeStation/NSV13, pull requests merged in 2020-12, with the labels that each got.

#1113 Stop mining ship damage affecting the main overmap
  nsv13/code/modules/overmap/ftl.dm
Labels: Fix

#1107 its a ship, not a station.
  code/modules/events/shuttle_loan.dm
Labels: Tweak

#1120 Replace TRUE with 1 in DMM files
  _maps/map_files/Gladius/Gladius1.dmm
  _maps/map_files/Gladius/Gladius2.dmm
Labels: Map Edit

#999 The Rook, A mining ship for the SGV Atherwhisp
  _maps/aetherwhisp.json
  _maps/map_files/Mining/nsv13/Rook.dmm
Labels: Active Test Merge, Feature, Map Edit

#1104 Brazil 2.5
  nsv13/code/controllers/subsystem/starsystem.dm
Labels: Feature, Fix

#1072 Adds engineering optional objectives
  nsv13.dme
  nsv13/code/modules/crew_objectives/engineering_objectives.dm
  nsv13/code/modules/power/rbmk.dm
  nsv13/code/modules/power/stormdrive.dm
Labels: Active Test Merge, Feature

#1074 Torpedo juice, munitions metabolism trait, and munitions paycheck department.
  code/__DEFINES/traits.dm
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  icons/obj/drinks.dmi
  nsv13/code/modules/jobs/job_types/air_traffic_controller.dm
  nsv13/code/modules/jobs/job_types/fighter_pilot.dm
  nsv13/code/modules/jobs/job_types/fighter_technician.dm
  nsv13/code/modules/jobs/job_types/master_at_arms.dm
  nsv13/code/modules/jobs/job_types/munitions_technician.dm
Labels: Active Test Merge, Feature, Sprites, Tweak

#1097 Changes tool sprites
  icons/mob/inhands/equipment/tools_lefthand.dmi
  icons/mob/inhands/equipment/tools_righthand.dmi
  icons/obj/tools.dmi
Labels: Active Test Merge, Feature, Removal, Sprites

#1109 adds the new projectile.dmi, credit to diedsniper
  nsv13/icons/obj/guns/projectile.dmi
Labels: Feature

#1103 Gives the UDK a new sprite and makes puce lockers work properly
  code/game/objects/items/devices/radio/encryptionkey.dm
  icons/obj/radio.dmi
  nsv13/icons/obj/custom_closet.dmi
  nsv13/icons/obj/custom_closets.dmi
Labels: Refactor, Sprites, Tweak

#1127 Adds hot crossed buns
  sound/roundend/hot_cross_buns.ogg
Labels: Feature, Sound

#1123 Allows the code to compile again
  code/__HELPERS/type2type.dm
  code/controllers/configuration/entries/resources.dm
  code/controllers/subsystem/assets.dm
  code/modules/antagonists/_common/antag_datum.dm
  code/modules/asset_cache/asset_cache_client.dm
  code/modules/asset_cache/asset_cache_item.dm
  code/modules/asset_cache/asset_list.dm
  code/modules/asset_cache/transports/asset_transport.dm
  code/modules/client/asset_cache.dm
  code/modules/client/client_defines.dm
  nsv13.dme
Labels: Config Update, Fix

#1133 Revert "Allows the code to compile again"
  code/__HELPERS/type2type.dm
  code/controllers/configuration/entries/resources.dm
  code/controllers/subsystem/assets.dm
  code/modules/antagonists/_common/antag_datum.dm
  code/modules/asset_cache/asset_cache_client.dm
  code/modules/asset_cache/asset_cache_item.dm
  code/modules/asset_cache/asset_list.dm
  code/modules/asset_cache/transports/asset_transport.dm
  code/modules/client/asset_cache.dm
  code/modules/client/client_defines.dm
  nsv13.dme
Labels: Config Update, Revert

#1134 Revert "Sanitize tips (#3077)"
  code/modules/antagonists/_common/antag_datum.dm
  code/modules/antagonists/_common/tips.dm
  code/modules/antagonists/traitor/datum_traitor.dm
Labels: Revert

#1124 Fixes multitool bug with APNW/APNP
  nsv13/code/modules/overmap/armour/nano_pump.dm
Labels: Fix

#1141 Allows CI to pass again
  code/game/mecha/mech_fabricator.dm
  nsv13/code/controllers/subsystem/starsystem.dm
  nsv13/code/modules/collision/shape.dm
  tools/WebhookProcessor/github_webhook_processor.php
Labels: Fix, Tools

#1125 Removes fleet and grand admiral gear in the stateroom on the gladius, and replaces it with normal admiral clothes
  _maps/map_files/Gladius/Gladius1.dmm
Labels: Map Edit, Removal, Tweak

#1139 Makes inflatable walls actually block air
  nsv13/code/game/general_quarters/squad_items.dm
Labels: Fix

#1140 fixes tactical computer and gauss gun ssding breaking them
  code/modules/mob/living/logout.dm
  nsv13/code/modules/overmap/components.dm
Labels: Fix

#1138 Semmes for Debugging
  _maps/destroyer.dm
  _maps/destroyer.json
  _maps/map_files/missileboat/combined_dev.dmm
  _maps/shuttles/turbolifts/aircraft_semmes.dmm
  code/datums/shuttles.dm
  code/game/area/Space_Station_13_areas.dm
  code/game/objects/effects/spawners/structure.dm
  code/game/objects/structures/railings.dm
  code/game/turfs/open/floor/misc_floor.dm
  config/game_options.txt
  config/maps.txt
  nsv13/code/game/turfs/wall.dm
  nsv13/code/modules/power/rbmk.dm
  nsv13/game/areas.dm
Labels: Config Update, Map Edit

#1151 Fixes Linters
  _maps/shuttles/turbolifts/aircraft_semmes.dmm
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Fix, Map Edit, UI

#1146 Smarter FTL AI
  nsv13.dme
  nsv13/code/_DEFINES/fleets.dm
  nsv13/code/controllers/subsystem/starsystem.dm
  nsv13/code/modules/overmap/ai-skynet2.dm
  nsv13/code/modules/overmap/factions.dm
  nsv13/code/modules/overmap/fleet_ftl_pathfinding.dm
Labels: Feature, UI
