Repository BeeStation/NSV13, pull requests merged in 2020-03, with the labels that each got.

#352 Adds a proper library to the SGC Enterprise
  _maps/map_files/Enterprise/Enterprise1.dmm
  _maps/map_files/Enterprise/Enterprise2.dmm
Labels: Feature, Map Edit

#353 Fixing more Enterprise debt
  _maps/map_files/Enterprise/Enterprise1.dmm
  _maps/map_files/Enterprise/Enterprise2.dmm
Labels: Map Edit

#355 Fixes AI camera
  nsv13/code/modules/overmap/camera.dm
Labels: Fix

#339 SSstarsystem + "NSV13" gameplay systems update
  nsv13.dme
  nsv13/_DEFINES/overmap.dm
  nsv13/code/controllers/subsystem/starsystem.dm
  nsv13/code/modules/events/overmap/_overmap_event_handler.dm
  nsv13/code/modules/events/overmap/belt_rats.dm
  nsv13/code/modules/events/overmap/lone_hunter.dm
  nsv13/code/modules/overmap/ai.dm
  nsv13/code/modules/overmap/ai_interiors.dm
  nsv13/code/modules/overmap/fighters/fighters.dm
  nsv13/code/modules/overmap/ftl.dm
  nsv13/code/modules/overmap/overmap.dm
  nsv13/code/modules/overmap/types.dm
  nsv13/code/modules/overmap/weapons.dm
  nsv13/code/modules/power/stormdrive.dm
Labels: Feature, Fix, National Debt, Refactor

#306 Count Honkula's crypt
  _maps/map_files/Mining/nsv13/ruins/mining5.dmm
  nsv13.dme
  nsv13/code/modules/mob/living/simple_animal/hostile/dioclown.dm
  nsv13/icons/mob/animal.dmi
  nsv13/icons/mob/mask.dmi
  nsv13/icons/obj/clothing/masks.dmi
Labels: Feature, Map Edit

#350 Railgun aimer
  code/_onclick/drag_drop.dm
  nsv13.dme
  nsv13/code/modules/overmap/aim_helper.dm
  nsv13/code/modules/overmap/overmap.dm
  nsv13/code/modules/overmap/weapons.dm
Labels: Feature

#371 disco inferno precursor
  code/datums/armor.dm
Labels: Feature

#375 Security level lowers to blue after dispatching all targets in a system
  config/game_options.txt
  nsv13/code/controllers/subsystem/starsystem.dm
Labels: Config Update, Tweak

#351 Makes admin get() work on fighter occupants
  code/modules/admin/verbs/adminjump.dm
  nsv13/code/modules/overmap/camera.dm
  nsv13/code/modules/overmap/fighters/fighters.dm
Labels: Administration, Fix, Refactor

#367 Binoculars + other twohanded fixes
  code/game/objects/items/twohanded.dm
  code/modules/awaymissions/capture_the_flag.dm
  code/modules/mining/ores_coins.dm
  code/modules/research/xenobiology/crossbreeding/_weapons.dm
Labels: Fix

#376 Port FTLiver
  icons/obj/drinks.dmi
  nsv13.dme
  nsv13/code/modules/food_and_drinks/drinks/drinks.dm
  nsv13/code/modules/food_and_drinks/recipes/drinks_recipes.dm
  nsv13/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
Labels: Feature, Sprites

#373 Mining Mapfixes
  _maps/map_files/Mining/nsv13/nostromo.dmm
  _maps/map_files/Mining/nsv13/ruins/mining5.dmm
Labels: Map Edit

#379 New Mining Asteroids
  _maps/map_files/Mining/nsv13/asteroids/asteroid4.dmm
  _maps/map_files/Mining/nsv13/ruins/mining6.dmm
Labels: Feature, Map Edit

#385 [Port][s] Fixes XSS Exploit Defeating Sanitization of Any Strin… (#1334)
  code/modules/goonchat/browserassets/js/browserOutput.js
Labels: FUCK, Priority: High, bug, security

#125 [READY] Vago Class Light Missile Cruiser
  _maps/Vago.dm
  _maps/map_files/Mining/nsv13/FOB_Shuttle.dmm
  _maps/map_files/Vago/overmap.dmm
  _maps/map_files/Vago/vagodeck1.dmm
  _maps/map_files/Vago/vagodeck2.dmm
  _maps/shuttles/nsv/nsv_vago.dmm
  _maps/vago.json
  code/controllers/subsystem/mapping.dm
  config/maps.txt
  nsv13/game/areas.dm
Labels: Config Update, Feature, Map Edit, Needs Review, Pre-BeeBase

#390 [PORT] Beestation #1344 (Unban panel fix)
  code/modules/admin/sql_ban_system.dm
Labels: Administration

#347 [READY] NSV Hammerhead additions and fixes
  _maps/map_files/Hammerhead/Hammerhead.dmm
  _maps/shuttles/cargo_hammerhead.dmm
Labels: Active Test Merge, Map Edit, Needs Review, Needs Test Merge

#397 Fixes some issues with the MAA
  nsv13/code/game/objects/items/munitions_items.dm
  nsv13/code/game/objects/structures/munitions_closets.dm
  nsv13/code/modules/jobs/job_types/master_at_arms.dm
Labels: Feature, Fix

#399 Fixes bad minetype handling
  code/controllers/subsystem/mapping.dm
Labels: Code Improvement

#383 Restores barricade construction
  code/game/objects/items/stacks/sheets/sheet_types.dm
Labels: Feature, Fix

#381 Fixes some minor issues with ship construction
  code/__DEFINES/is_helpers.dm
  code/game/objects/items/RCD.dm
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/grille.dm
  code/game/turfs/simulated/floor.dm
  code/game/turfs/simulated/floor/misc_floor.dm
  code/game/turfs/simulated/floor/plasteel_floor.dm
  nsv13/code/game/objects/effects/spawners/structure.dm
  nsv13/game/custom_materials.dm
  nsv13/game/custom_turfs.dm
Labels: Feature, Fix

#403 Fixes MAA headset
  nsv13/code/game/objects/items/munitions_items.dm
Labels: Fix

#405 Fixes peacekeeper mags
  nsv13/game/custom_guns.dm
Labels: Fix

#404 Changes cross-server news report agent
  code/controllers/subsystem/ticker.dm
Labels: Tweak
