Repository BeeStation/NSV13, pull requests merged in 2020-05, with the labels that each got.

#547 Multiple Map Bug Fixes
  _maps/map_files/Enterprise/Enterprise1.dmm
  _maps/map_files/Enterprise/Enterprise2.dmm
  _maps/map_files/Hammerhead/Hammerhead.dmm
  _maps/map_files/Vago/vagodeck1.dmm
Labels: Feature, Fix, Map Edit, Tweak

#519 Galactica Spacetrials
  _maps/_basemap.dm
  _maps/galactica.dm
  _maps/galactica.json
  _maps/map_files/Galactica/Galactica.dmm
  _maps/map_files/Galactica/Galactica2.dmm
  _maps/map_files/Galactica/job_changes.dm
  _maps/map_files/Galactica/overmap.dmm
  _maps/shuttles/ferry_galactica.dmm
  _maps/shuttles/turbolifts/nsv/turbolift_galactica.dmm
  _maps/shuttles/turbolifts/nsv/turbolift_galactica_secondary.dmm
  code/controllers/subsystem/vis_overlays.dm
  config/maps.txt
  icons/obj/decals.dmi
  icons/turf/floors.dmi
  nsv13.dme
  nsv13/code/datums/holocall.dm
  nsv13/code/datums/shuttles.dm
  nsv13/code/game/objects/structures/custom_computers.dm
  nsv13/code/modules/overmap/fighters/fighters.dm
  nsv13/code/modules/overmap/types.dm
  nsv13/code/modules/turbolift/turbolift.dm
  nsv13/game/custom_turfs.dm
  nsv13/goonstation/icons/obj/computer.dmi
  nsv13/icons/overmap/nanotrasen/Battleship.dmi
Labels: Config Update, Map Edit, Sprites

#536 (Ready) Fixes slideshow mode
  code/__DEFINES/cleaning.dm
  code/datums/components/decal.dm
  code/game/objects/effects/decals/decal.dm
  code/modules/projectiles/projectile.dm
  nsv13/code/__HELPERS/priority_announce.dm
  nsv13/code/_onclick/hud/parallax.dm
  nsv13/code/controllers/subsystem/processing/overmap.dm
  nsv13/code/modules/overmap/camera.dm
  nsv13/code/modules/overmap/overmap.dm
  nsv13/code/modules/overmap/physics.dm
Labels: Map Issue, Tweak

#590 fighter control console circuit - research + print
  nsv13/code/modules/overmap/fighters/control_console.dm
  nsv13/code/modules/overmap/fighters/fighters_components.dm
Labels: Feature

#574 [s] Paper exploit
  code/modules/paperwork/paper.dm
Labels: Tweak, security

#569 Fixes Tyrosene fuel pump cargo crate
  nsv13/code/modules/cargo/packs.dm
  nsv13/code/modules/overmap/fighters/fighters_components.dm
Labels: Fix

#509 Adds a lot of inhand sprites for minerals and sheets
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/stacks/sheets/sheets.dm
  nsv13/icons/mob/inhands/misc/sheets_lefthand.dmi
  nsv13/icons/mob/inhands/misc/sheets_righthand.dmi
Labels: Active Test Merge, Sprites

#501 [FIX] Full auto improvements
  code/_onclick/drag_drop.dm
  code/modules/projectiles/gun.dm
  nsv13.dme
  nsv13/code/_onclick/drag_drop.dm
Labels: Feature, Fix

#594 Various bugfixes and QOL
  icons/effects/beam.dmi
  icons/obj/computer.dmi
  nsv13.dme
  nsv13/code/game/machinery/hologram.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/gauss_gun.dm
  nsv13/code/modules/overmap/camera.dm
  nsv13/code/modules/overmap/components.dm
  nsv13/code/modules/overmap/fighters/fighters_launcher.dm
  nsv13/code/modules/overmap/fighters/tug.dm
  nsv13/code/modules/overmap/overmap.dm
  nsv13/code/modules/overmap/radar.dm
  nsv13/code/modules/power/stormdrive.dm
  nsv13/code/modules/vehicles/_vehicle.dm
  nsv13/goonstation/icons/obj/computer.dmi
  nsv13/sound/effects/computer/admin_holopad_activate.ogg
  tgui-next/packages/tgui/interfaces/FighterLauncher.js
  tgui-next/packages/tgui/public/tgui.bundle.js
  tgui-next/packages/tgui/routes.js
  tgui/assets/tgui.js
  tgui/src/interfaces/fighter_tug.ract
Labels: Fix, Sprites, UI

#591 fighter build clarification + passenger seat change
  nsv13/code/modules/overmap/fighters/fighters.dm
  nsv13/code/modules/overmap/fighters/heavy_build.dm
  nsv13/code/modules/overmap/fighters/utility_build.dm
Labels: Refactor, Tweak

#550 [DNM][WIP]Donator Items
  code/__DEFINES/misc.dm
  code/controllers/configuration/configuration.dm
  code/modules/client/loadout/loadout.dm
  code/modules/client/loadout/loadout_donator.dm
  code/modules/client/preferences.dm
  code/modules/jobs/job_types/_job.dm
  config/donators.txt
  nsv13.dme
Labels: Config Update, Do Not Merge, FUCK, Work In Progress

#573 Disco Inferno P3
  nsv13/code/modules/mining/asteroid.dm
  nsv13/code/modules/munitions/ammunition/torpedos/torpedo_types.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/flak.dm
  nsv13/code/modules/overmap/ai.dm
  nsv13/code/modules/overmap/fighters/heavy.dm
  nsv13/code/modules/overmap/fighters/light.dm
  nsv13/code/modules/overmap/fighters/utility.dm
  nsv13/code/modules/overmap/types.dm
  nsv13/code/modules/overmap/weapons.dm
  nsv13/game/custom_turfs.dm
Labels: Balance/Rebalance, Feature, VIBE CHECK

#614 Security Hotpatch 5/22/20
  code/modules/admin/verbs/adminpm.dm
  code/modules/client/verbs/ooc.dm
Labels: security

#609 Skynet AI
  icons/obj/projectiles.dmi
  nsv13.dme
  nsv13/code/controllers/subsystem/starsystem.dm
  nsv13/code/datums/weapon_types.dm
  nsv13/code/modules/munitions/munitions_computer.dm
  nsv13/code/modules/munitions/ship_weapons/_ship_weapon.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/flak.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/gauss_gun.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/pdc.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/railgun.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/torpedo_launcher.dm
  nsv13/code/modules/overmap/ai-skynet.dm
  nsv13/code/modules/overmap/ai.dm
  nsv13/code/modules/overmap/components.dm
  nsv13/code/modules/overmap/fighters/fighters.dm
  nsv13/code/modules/overmap/fighters/heavy.dm
  nsv13/code/modules/overmap/fighters/light.dm
  nsv13/code/modules/overmap/ftl.dm
  nsv13/code/modules/overmap/overmap.dm
  nsv13/code/modules/overmap/physics.dm
  nsv13/code/modules/overmap/types.dm
  nsv13/code/modules/overmap/weapons.dm
  nsv13/code/modules/overmap/weapons/damage.dm
  nsv13/code/modules/overmap/weapons/projectiles_fx.dm
  nsv13/code/modules/overmap/weapons/ship_weapon.dm
  nsv13/code/modules/overmap/weapons/weapons2.dm
  nsv13/icons/overmap/nanotrasen/ai_fighter.dmi
  nsv13/icons/overmap/syndicate/syn_bomber.dmi
  nsv13/sound/effects/fighters/BRRTTTTTT.ogg
  nsv13/sound/effects/fighters/BRRTTTTTT.wav
  nsv13/sound/effects/fighters/autocannon.ogg
  nsv13/sound/weapons/pdc_multi.ogg
  nsv13/sound/weapons/pdc_single.ogg
Labels: Feature, Sprites

#626 Whoops
  nsv13/code/datums/weapon_types.dm
  nsv13/code/modules/overmap/ai-skynet.dm
Labels: Fix

#583 [READY] NSV Galactica fixes and service redo
  _maps/map_files/Galactica/Galactica.dmm
  _maps/map_files/Galactica/Galactica2.dmm
  _maps/shuttles/ferry_galactica.dmm
Labels: Feature, Fix, Map Edit, Needs Review

#610 Map fixes
  _maps/map_files/Enterprise/Enterprise2.dmm
  _maps/map_files/Galactica/Galactica.dmm
  _maps/map_files/Galactica/Galactica2.dmm
  _maps/map_files/Hammerhead/Hammerhead.dmm
  _maps/map_files/Vago/vagodeck2.dmm
Labels: Feature, Fix, Map Edit, Tweak

#625 Correct materials for NSV alloys
  nsv13/code/modules/research/designs/smelting_designs.dm
  nsv13/game/custom_materials.dm
Labels: Fix

#640 Fixes Torp Casing bug when constructing in a trolley, but the root cause needs work.
  nsv13/code/modules/munitions/ammunition/torpedos/torpedo_construction.dm
Labels: Fix, Needs Test Merge
