Repository BeeStation/NSV13, pull requests merged in 2020-10, with the labels that each got.

#819 NSV Pegasus - The battleship
  _maps/map_files/Pegasus/job_changes.dm
  _maps/map_files/Pegasus/pegasus1.dmm
  _maps/map_files/Pegasus/pegasus2.dmm
  _maps/pegasus.dm
  _maps/pegasus.json
  code/__DEFINES/nsv13.dm
  code/modules/jobs/map_changes/map_changes.dm
  config/maps.txt
  nsv13.dme
  nsv13/code/_HELPERS/overmap.dm
  nsv13/code/game/area/pegasus.dm
  nsv13/code/game/general_quarters/damage.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/flak.dm
  nsv13/code/modules/overmap/ai-skynet2.dm
  nsv13/code/modules/overmap/armour/nano_well.dm
  nsv13/code/modules/overmap/overmap.dm
  nsv13/code/modules/overmap/types/nanotrasen.dm
  nsv13/code/modules/overmap/weapons/projectiles_fx.dm
  nsv13/game/objects/pool/pool.dm
  nsv13/game/objects/pool/pool_items.dm
Labels: Config Update, Feature, Map Edit, Needs Test Merge

#912 NSV13 Gases - Lung Interactions Monstermos Compliance Pass
  code/modules/surgery/organs/lungs.dm
Labels: Fix

#911 Fixes ghosts being able to use the astrometrics computer + Roci's Dradis is no longer useable by all
  nsv13/code/modules/overmap/components.dm
  nsv13/code/modules/overmap/ftl.dm
  nsv13/code/modules/overmap/radar.dm
  nsv13/code/modules/overmap/starmap.dm
  nsv13/code/modules/research/astrometrics.dm
Labels: Fix

#899 Adds sprites for burnt nsv floors and cleans up unneeded base code changes [Ready]
  code/game/turfs/open/floor/misc_floor.dm
  icons/turf/floors.dmi
  nsv13/game/custom_turfs.dm
  nsv13/icons/turf/floors.dmi
Labels: Feature, Fix, Needs Review, Sprites

#842 MAC Construction
  code/game/objects/items/stacks/sheets/sheet_types.dm
  nsv13.dme
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/mac.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/mac_construction.dm
  nsv13/code/modules/munitions/ship_weapons/ship_weapon_parts.dm
  nsv13/game/custom_materials.dm
  nsv13/icons/obj/items_and_weapons.dmi
Labels: Feature, Needs Test Merge

#908 Stormdrive Phase 4
  nsv13/code/modules/cargo/packs.dm
  nsv13/code/modules/power/stormdrive.dm
Labels: Feature, Refactor

#898 APNW 1.2 - Starmap 2 Edition
  nsv13/code/modules/overmap/armour/nano_pump.dm
  nsv13/code/modules/overmap/armour/nano_well.dm
  nsv13/icons/obj/objects.dmi
  tgui/packages/tgui/interfaces/ArmourPlatingNanorepairWell.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Feature, UI

#910 Reworks the FOB
  _maps/map_files/Mining/nsv13/Whisp_FOB.dmm
Labels: Map Edit

#922 Stormdrive Interim Fixes
  code/game/objects/items/devices/anomaly_neutralizer.dm
  nsv13/code/modules/power/stormdrive.dm
Labels: Fix

#919 Munitions - MAA Consoles Update
  nsv13/code/modules/overmap/components.dm
  tgui/packages/tgui/interfaces/OrdnanceConsole.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Feature, Fix, UI

#914 Stormdrive Mod Comp Program
  nsv13/code/modules/power/stormdrive.dm
  tgui/packages/tgui/interfaces/NtosStormdriveMonitor.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Feature, Fix, UI

#902 Hammerhead atmos 2
  _maps/map_files/Hammerhead/Hammerhead.dmm
Labels: Map Edit, Tweak

#915 Munitions Wardrobe Vendor + Backpacks
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/modules/goonchat/browserassets/css/browserOutput.css
  code/modules/goonchat/browserassets/css/browserOutput_white.css
  icons/mob/back.dmi
  interface/stylesheet.dm
  nsv13/code/game/machinery/munitions_machinery.dm
  nsv13/code/game/objects/items/munitions_items.dm
  nsv13/code/game/objects/structures/custom_closets.dm
  nsv13/code/game/objects/structures/munitions_closets.dm
  nsv13/code/modules/cargo/packs.dm
  nsv13/code/modules/jobs/job_types/air_traffic_controller.dm
  nsv13/code/modules/jobs/job_types/fighter_pilot.dm
  nsv13/code/modules/jobs/job_types/fighter_technician.dm
  nsv13/code/modules/jobs/job_types/master_at_arms.dm
  nsv13/code/modules/jobs/job_types/munitions_technician.dm
  nsv13/icons/mob/inhands/backpack_lefthand.dmi
  nsv13/icons/mob/inhands/backpack_righthand.dmi
  nsv13/icons/obj/custom_vendors.dmi
  nsv13/icons/obj/storage.dmi
Labels: Feature, Sprites

#929 Mapps
  _maps/map_files/Aetherwhisp/Aetherwhisp2.dmm
  _maps/map_files/Hammerhead/Hammerhead.dmm
  _maps/map_files/Jeppison/Jeppison1.dmm
  _maps/map_files/Jeppison/Jeppison2.dmm
  _maps/map_files/Pegasus/pegasus2.dmm
  _maps/map_files/Tycoon/Tycoon2.dmm
  _maps/map_files/jollysausage/todger.dmm
Labels: Feature, Fix, Map Edit

#926 Salvagemap 2
  icons/effects/parallax.dmi
  nsv13.dme
  nsv13/_DEFINES/overmap.dm
  nsv13/code/_DEFINES/missions.dm
  nsv13/code/_HELPERS/overmap.dm
  nsv13/code/controllers/subsystem/starsystem.dm
  nsv13/code/datums/components/missions.dm
  nsv13/code/datums/missions.dm
  nsv13/code/modules/cargo/mission_cargos.dm
  nsv13/code/modules/events/overmap/_overmap_event_handler.dm
  nsv13/code/modules/overmap/ai-skynet2.dm
  nsv13/code/modules/overmap/factions.dm
  nsv13/code/modules/overmap/fighters/fighters2.dm
  nsv13/code/modules/overmap/ftl.dm
  nsv13/code/modules/overmap/overmap.dm
  nsv13/code/modules/overmap/radar.dm
  nsv13/code/modules/overmap/starmap.dm
  nsv13/code/modules/overmap/traders.dm
  nsv13/code/modules/overmap/traders_items.dm
  nsv13/icons/obj/fighter_components.dmi
  nsv13/icons/overmap/nanotrasen/carrier.dmi
  nsv13/icons/overmap/nanotrasen/fighter.dmi
  nsv13/icons/overmap/nanotrasen/heavy_fighter.dmi
  nsv13/icons/overmap/neutralstation.dmi
  tgui/packages/tgui/interfaces/Dradis.js
  tgui/packages/tgui/interfaces/Starmap.js
  tgui/packages/tgui/interfaces/Trader.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Sprites, UI

#931 Alice and bob are the hottest couple on the planet, change my mind
  _maps/map_files/Jeppison/Jeppison1.dmm
  _maps/map_files/Pegasus/pegasus1.dmm
  _maps/map_files/Tycoon/Tycoon2.dmm
  _maps/map_files/jollysausage/todger.dmm
Labels: Map Edit

#935 Fixes a couple issues that cropped up during testing
  nsv13/code/_onclick/hud/parallax.dm
  nsv13/code/controllers/subsystem/starsystem.dm
  nsv13/code/modules/overmap/factions.dm
Labels: Fix

#936 Whoops
  nsv13/code/modules/overmap/ai-skynet2.dm
Labels: Fix

#943 APNW bug fix
  nsv13/code/modules/overmap/armour/nano_well.dm
Labels: Fix

#924 Makes you unable to toggle munitions trolley brakes from a distance
  nsv13/code/modules/munitions/munitions_trolley.dm
Labels: Fix

#938 NSV sheet names
  nsv13/game/custom_materials.dm
Labels: Fix

#956 Nothing Went Wrong!
  _maps/map_files/Hammerhead/Hammerhead.dmm
Labels: Fix, Map Edit, Priority: High

#939 #885 Replacement - Part 1
  code/modules/cargo/packs.dm
Labels: Removal, Tweak

#940 #885 Replacement - Part 2
  nsv13/code/modules/cargo/packs.dm
Labels: Feature, Tweak

#917 Multi-Z Crew Monitoring
  code/game/machinery/computer/crew.dm
  code/game/objects/items/pinpointer.dm
Labels: Tweak

#957 Nothing Went Wrong! v2 (Discordant fusion noises)
  _maps/map_files/Hammerhead/Hammerhead.dmm
  _maps/map_files/Pegasus/pegasus2.dmm
Labels: Fix, Map Edit, Priority: High, Tweak

#948 Add missing categories to the techfab
  code/modules/research/machinery/techfab.dm
Labels: Fix

#968 Allows teleportation on the mining ship
  nsv13/game/areas.dm
Labels: Fix

#953 Makes Jolly Sausages toxins not shit.
  _maps/map_files/jollysausage/todger.dmm
Labels: Map Edit

#965 Fixes some issues on the Pegasus
  _maps/map_files/Pegasus/pegasus2.dmm
Labels: Feature, Map Edit, Removal

#981 adds a protective nanocarbon glass wall to the tycoons cooling loop
  _maps/map_files/Tycoon/Tycoon2.dmm
Labels: Map Edit

#988 Tycoon fixes
  _maps/map_files/Tycoon/Tycoon1.dmm
Labels: Feature, Map Edit

#987 APNP bug fix
  nsv13/code/modules/overmap/armour/nano_pump.dm
Labels: Fix

#944 Battleship overmap changes
  nsv13/code/modules/overmap/types/nanotrasen.dm
Labels: Balance/Rebalance

#923 Nuke summoning device no longer spawns in the syndie captain's backpack
  _maps/map_files/PVP/Hammurabi.dmm
  nsv13/code/game/gamemodes/pvp/pvp.dm
Labels: Fix, Map Edit, Tweak

#955 lets the rest of the crew know when you are talking shit to other ships
  nsv13/code/modules/overmap/ai-skynet2.dm
  nsv13/code/modules/overmap/radar.dm
Labels: Feature, Fix

#1003 Prevents circumvention of weapon lubrication oil use
  nsv13/code/modules/munitions/ship_weapons/ship_weapon_maintenance.dm
Labels: Fix

#1008 Minimum player count check on syndicate boarders
  nsv13/code/modules/overmap/boarding/boarding.dm
Labels: Feature

#1009 Clone pod construction fix
  code/game/machinery/cloning.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
Labels: Fix
