Repository BeeStation/NSV13, pull requests merged in 2020-11, with the labels that each got.

#985 Adds a QM locker to the jolly sausage
  _maps/map_files/jollysausage/todger.dmm
Labels: Fix, Map Edit

#1000 [Testing required] Allows you to actually win the game again.
  nsv13/code/modules/overmap/ai-skynet2.dm
  nsv13/code/modules/overmap/fighters/fighters2.dm
  nsv13/code/modules/overmap/types/nanotrasen.dm
Labels: Active Test Merge, Fix

#1019 Admin toggle for boarders
  code/modules/admin/admin_verbs.dm
  nsv13/code/controllers/subsystem/starsystem.dm
  nsv13/code/modules/overmap/boarding/boarding.dm
Labels: Administration

#930 Hammerhead fixes and stuff
  _maps/map_files/Hammerhead/Hammerhead.dmm
Labels: Active Test Merge, Map Edit

#1028 Fixes RBMK valve control console exploitability
  nsv13/code/modules/power/rbmk.dm
Labels: Fix

#1034 Makes HH distro and scrubbers not linked anymore
  _maps/map_files/Hammerhead/Hammerhead.dmm
Labels: Map Edit

#1042 [Fix] Resolves an issue with physics component dereferencing
  nsv13/code/modules/overmap/physics2d.dm
Labels: Fix

#1024 Fixing Jeppison
  _maps/map_files/Jeppison/Jeppison1.dmm
  _maps/map_files/Jeppison/Jeppison2.dmm
  _maps/map_files/Mining/nsv13/Whisp_FOB.dmm
Labels: Active Test Merge, Map Edit

#1031 Stormdrive Gas Tweaks - Again
  nsv13/code/modules/power/stormdrive.dm
  tgui/packages/tgui/interfaces/StormdriveConsole.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Tweak, UI

#1044 very important fix
  code/game/objects/items/charter.dm
Labels: Fix

#1036 [s] Type checking for cargo holds
  nsv13/code/modules/overmap/fighters/fighters2.dm
Labels: Fix

#983 Overmap Shield Tech -> Data Disk
  nsv13/code/modules/overmap/shieldgen.dm
  nsv13/code/modules/overmap/traders.dm
  nsv13/code/modules/overmap/traders_items.dm
Labels: Feature, Removal

#1050 [s] Fixes some lag
  nsv13/code/modules/overmap/aim_helper.dm
Labels: FUCK, Priority: High

#1047 Fix JSON verifier only verifying the very first JSON file
  .vscode/settings.json
  tools/json_verifier.py
Labels: Tools

#1046 should fix LOOC
  code/modules/client/verbs/looc.dm
Labels: Active Test Merge, Administration, Fix

#1058 fixes fighters leaving ships other than the main overmap
  nsv13/code/modules/overmap/fighters/fighters_launcher.dm
Labels: Fix

#1054 lets travis greentext
  _maps/map_files/Hammerhead/Hammerhead.dmm
Labels: Map Edit

#967 updates ethereals to TG high demand high compensation dynamic
  code/__DEFINES/mobs.dm
  code/modules/power/apc.dm
  code/modules/power/cell.dm
  code/modules/power/lighting.dm
  code/modules/surgery/organs/stomach.dm
Labels: Active Test Merge, Balance/Rebalance

#1027 Armor increasing fighter max hp is no longer completely useless
  nsv13/code/modules/overmap/fighters/fighters2.dm
Labels: Active Test Merge, Fix

#1013 missions 2
  nsv13.dme
  nsv13/code/controllers/subsystem/starsystem.dm
  nsv13/code/datums/components/missions.dm
  nsv13/code/datums/missions.dm
  nsv13/code/modules/cargo/mission_cargos.dm
  nsv13/code/modules/cargo/mission_rewards.dm
  nsv13/code/modules/munitions/ammunition/torpedos/torpedo_types.dm
  nsv13/code/modules/munitions/ship_weapons/energy_weapons/phaser.dm
  nsv13/code/modules/overmap/overmap.dm
  nsv13/code/modules/overmap/traders.dm
  nsv13/code/modules/ship_missions/hail_computer.dm
  nsv13/icons/obj/custom_crates.dmi
  tgui/packages/tgui/interfaces/NtosHailLogs.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Active Test Merge, Code Improvement, TGUI, UI

#1040 New map: NSV Eclipse
  _maps/Eclipse.dm
  _maps/eclipse.json
  _maps/map_files/Eclipse/Eclipse.dmm
  _maps/map_files/Eclipse/job_changes.dm
  code/controllers/subsystem/mapping.dm
  code/datums/map_config.dm
  code/modules/jobs/map_changes/map_changes.dm
  config/maps.txt
Labels: Active Test Merge, Config Update, Feature, Map Edit

#1053 Munitions budget card sprite
  icons/obj/card.dmi
  nsv13/code/game/objects/items/munitions_items.dm
Labels: Feature, Sprites

#1066 Reduce power usage of viewscreens and lore terminals
  nsv13/code/modules/overmap/components.dm
  nsv13/game/lore_terminal.dm
Labels: Tweak

#1049 Jepisson Server Freezer Fix
  _maps/map_files/Jeppison/Jeppison2.dmm
Labels: Map Edit

#1035 Makes pilots not get deleted (Should fix uncloneability)
  nsv13/code/modules/overmap/fighters/fighters2.dm
Labels: Active Test Merge, Fix

#994 Mining Ship Tweaks
  _maps/map_files/Mining/nsv13/FOB_Shuttle.dmm
  _maps/map_files/Mining/nsv13/Rocinante.dmm
  _maps/map_files/Mining/nsv13/Whisp_FOB.dmm
  _maps/map_files/Mining/nsv13/nostromo.dmm
  _maps/map_files/NSV Storage/Mining/Hephaestus/Hephaestus1.dmm
  nsv13/code/modules/mining/asteroid.dm
  nsv13/code/modules/overmap/ftl.dm
  nsv13/code/modules/overmap/radar.dm
Labels: Map Edit, Needs Test Merge, Tweak

#1068 Add cameras to the DMC Rocinante
  _maps/map_files/Mining/nsv13/Rocinante.dmm
Labels: Feature, Map Edit

#1082 starsystem change - Dolos-B-Gone
  nsv13/code/controllers/subsystem/starsystem.dm
Labels: Tweak

#1057 #1031 Wasn't Finished - Why you do this to me?
  nsv13/code/modules/power/stormdrive.dm
  tgui/packages/tgui/interfaces/NtosStormdriveMonitor.js
  tgui/packages/tgui/interfaces/StormdriveConsole.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Active Test Merge, Feature, UI

#1089 Eclipse fighter launcher is totally indestructible
  _maps/map_files/Eclipse/Eclipse.dmm
Labels: Map Edit

#1065 Replace old railgun rods with a new sprite
  nsv13/icons/obj/items_and_weapons.dmi
Labels: Feature

#1102 [s] Fixes firing electronics being able to skip most construction steps of ALL main ship weapons
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/mac_construction.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/railgun_construction.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/torpedo_launcher_construction.dm
Labels: Fix

#1095 Fixes some camera errors, fighter docking slightly cleaned up
  _maps/map_files/Instanced/map_files/SpaceSHIP.dmm
  nsv13/code/game/gamemodes/pvp/items.dm
  nsv13/code/modules/overmap/fighters/fighters_launcher.dm
Labels: Fix, Map Edit

#1052 New Map: NSV Gladius
  _maps/_basemap.dm
  _maps/gladius.dm
  _maps/gladius.json
  _maps/map_files/Gladius/Gladius1.dmm
  _maps/map_files/Gladius/Gladius2.dmm
  _maps/shuttles/arrival_gladius.dmm
  _maps/shuttles/cargo_gladius.dmm
  code/datums/shuttles.dm
  config/maps.txt
  nsv13/code/datums/shuttles.dm
  nsv13/game/areas.dm
  nsv13/game/custom_turfs.dm
  strings/station_names.txt
Labels: Active Test Merge, Config Update, Map Edit

#1092 Kudzu Fixu
  code/modules/events/spacevine.dm
  code/modules/mob/living/simple_animal/hostile/venus_human_trap.dm
Labels: Code Improvement, Fix, Tweak

#1062 Fixes issue #978 - Ion sabre not stunning
  nsv13/game/custom_items.dm
Labels: Active Test Merge

#1056 Jolly Sausage REEEWorks
  _maps/map_files/jollysausage/todger.dmm
Labels: Active Test Merge, Feature, Fix, Map Edit, Tweak

#1088 Disables lazy mode power supply
  code/modules/cargo/packs.dm
Labels: Removal

#1091 Various Eclipse fixes
  _maps/map_files/Eclipse/Eclipse.dmm
Labels: Feature, Fix, Map Edit

#1083 Brazil 2.0
  nsv13/code/controllers/subsystem/starsystem.dm
  nsv13/code/modules/overmap/ftl.dm
  nsv13/code/modules/overmap/starmap.dm
  nsv13/code/modules/overmap/traders.dm
Labels: Active Test Merge, Tweak

#989 Pegasus atmos changes
  _maps/map_files/Pegasus/pegasus1.dmm
Labels: Active Test Merge, Map Edit

#1096 Fix tuning fork atmos
  _maps/map_files/Instanced/map_files/SpaceSHIP.dmm
Labels: Map Edit

#1105 Fixes the reason recapturing systems didn't work.
  nsv13/code/modules/overmap/ai-skynet2.dm
Labels: Fix

#1106 Fixes torps being able to be transported in crates.
  code/game/objects/structures/crates_lockers/closets.dm
Labels: Fix

#1108 Fixing active turfs on CC z level
  _maps/map_files/generic/CentCom.dmm
Labels: Fix, Map Edit
