Repository BeeStation/NSV13, pull requests merged in 2021-03, with the labels that each got.

#1243 Gladius- Mail Mapping fix [Ready] Fixes issue #1182
  _maps/map_files/Gladius/Gladius1.dmm
  _maps/map_files/Gladius/Gladius2.dmm
Labels: Feature, Fix, Map Edit, Needs Review, Tweak

#1249 [Map] NSV Atlas, somehow smaller than eclipse! :tm:
  _maps/atlas.dm
  _maps/atlas.json
  _maps/map_files/Atlas/atlas.dmm
  _maps/map_files/Atlas/atlas2.dmm
  _maps/map_files/Atlas/job_changes.dm
  _maps/shuttles/arrival_atlas.dmm
  _maps/shuttles/cargo_atlas.dmm
  _maps/shuttles/emergency_atlas.dmm
  code/__DEFINES/maps.dm
  code/game/objects/effects/spawners/structure.dm
  code/modules/jobs/map_changes/map_changes.dm
  config/maps.txt
  nsv13/code/datums/shuttles.dm
Labels: Config Update, Feature, Map Edit

#1255 Gives MaA locker a munifab board
  nsv13/code/game/objects/structures/custom_closets.dm
Labels: Fix

#1266 Bridge Headset Rearrangement
  code/game/objects/items/devices/radio/headset.dm
  nsv13/code/game/objects/items/bridge_items.dm
  nsv13/code/game/objects/items/munitions_items.dm
Labels: Balance/Rebalance, Feature

#1110 Overhaul999
  _maps/map_files/Vago/vagodeck1.dmm
  _maps/map_files/Vago/vagodeck2.dmm
Labels: Map Edit, Tweak

#1268 Fixes a issue for ghosts. Simple issue.
  nsv13/code/modules/power/stormdrive.dm
Labels: Active Test Merge

#1254 PVP newnitions
  _maps/map_files/Instanced/babylonPVP.json
  _maps/map_files/Instanced/map_files/Babylon1.dmm
  _maps/map_files/Instanced/map_files/Babylon2.dmm
  code/__DEFINES/maps.dm
  code/game/objects/items/cards_ids.dm
  nsv13/code/game/gamemodes/pvp/pvp.dm
  nsv13/code/game/gamemodes/pvp/roles.dm
  nsv13/code/modules/mining/asteroid.dm
  nsv13/code/modules/overmap/ai-skynet2.dm
  nsv13/code/modules/overmap/types/syndicate.dm
  tgui/packages/tgui/interfaces/SecondaryID.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Active Test Merge, Config Update, Feature, Map Edit, UI

#1273 Fixes Atlas' missile factory
  _maps/map_files/Atlas/atlas.dmm
Labels: Active Test Merge, Fix, Map Edit

#1264 Even more fleet stuff
  nsv13/code/controllers/subsystem/starsystem.dm
  nsv13/code/modules/overmap/ai-skynet2.dm
  nsv13/code/modules/overmap/ftl.dm
  nsv13/code/modules/overmap/overmap.dm
Labels: Active Test Merge, Balance/Rebalance, Code Improvement, Fix

#1257 (Probably) fixes some problems with small-ship ftl-dragalong
  nsv13/code/modules/overmap/ftl.dm
Labels: Active Test Merge, Fix

#1239 Stops Suit Storage Units deleting (traitor objective) items when hacked or destroyed
  code/game/machinery/suit_storage_unit.dm
Labels: Active Test Merge, Feature, Fix

#1258 Makes ghosts unable to interact with TAC and Helm consoles
  nsv13/code/game/machinery/computer/_ship.dm
  nsv13/code/game/machinery/computer/tactical.dm
Labels: Active Test Merge, Fix

#1280 AI ships that aiprocess in nullspace now stop their own processing
  nsv13/code/modules/overmap/ai-skynet2.dm
Labels: Fix

#1287 Red Bursty Lasers
  nsv13/code/modules/munitions/ship_weapons/energy_weapons/phaser.dm
Labels: Fix

#1290 Fixes a *tiny* carrier fighter-launch issue
  nsv13/code/modules/overmap/ai-skynet2.dm
Labels: Fix

#1279 Munitions QOL pass!
  _maps/map_files/Atlas/atlas.dmm
  _maps/map_files/Atlas/atlas2.dmm
  _maps/map_files/Tycoon/Tycoon2.dmm
  code/game/objects/structures/ladders.dm
  icons/obj/computer.dmi
  nsv13/code/modules/munitions/ammunition/gauss_ammo.dm
  nsv13/code/modules/munitions/munitions_trolley.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/deck_guns.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/gauss_gun.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/revision2/automation.dm
  nsv13/code/modules/pool/pool_items.dm
  nsv13/code/modules/research/techweb/all_nsv_nodes.dm
  nsv13/icons/obj/munitions.dmi
  nsv13/icons/obj/munitions_large.dmi
  tgui/packages/tgui/interfaces/AmmoSorter.js
  tgui/packages/tgui/interfaces/MunitionsComputer.js
  tgui/packages/tgui/interfaces/MunitionsTrolley.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Active Test Merge, Feature, Map Edit, Sprites, Tweak, UI

#1282 Eclipse QOL changes
  _maps/map_files/Eclipse/Eclipse1.dmm
  _maps/map_files/Eclipse/Eclipse2.dmm
Labels: Active Test Merge, Feature, Map Edit, Tweak

#1302 [FIX] Resolve ammoRack BSOD
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/revision2/automation.dm
Labels: Active Test Merge, Fix

#1294 Fleet combat - Tabletop edition
  nsv13.dme
  nsv13/code/controllers/subsystem/starsystem.dm
  nsv13/code/modules/overmap/ai-skynet2.dm
  nsv13/code/modules/overmap/fleet_combat/combat_handling.dm
  nsv13/code/modules/overmap/fleet_combat/dice_datum.dm
  nsv13/code/modules/overmap/fleet_combat/solar_siege.dm
  nsv13/code/modules/overmap/overmap.dm
  nsv13/code/modules/overmap/types/nanotrasen.dm
  nsv13/code/modules/overmap/types/solgov.dm
  nsv13/code/modules/overmap/types/spacepirates.dm
  nsv13/code/modules/overmap/types/syndicate.dm
Labels: Active Test Merge, Feature

#1300 Allows the Ion sabre to actually hit things that aren't humans
  nsv13/code/game/objects/items/custom_items.dm
Labels: Active Test Merge, Fix
