Repository BeeStation/NSV13, pull requests merged in 2021-06, with the labels that each got.

#1360 Mass micro optimization, code cleaning, scientific accuracy and cryogenic fuels
  .vscode/settings.json
  _maps/map_files/Aetherwhisp/Aetherwhisp2.dmm
  _maps/map_files/Atlas/atlas.dmm
  _maps/map_files/Gladius/Gladius1.dmm
  _maps/map_files/Gladius/Gladius2.dmm
  _maps/map_files/Hammerhead/Hammerhead.dmm
  _maps/map_files/Instanced/map_files/Babylon1.dmm
  _maps/map_files/Instanced/map_files/SpaceSHIP.dmm
  _maps/map_files/Jeppison/Jeppison1.dmm
  _maps/map_files/Mining/nsv13/Rocinante.dmm
  _maps/map_files/Mining/nsv13/Whisp_FOB.dmm
  _maps/map_files/NSV Storage/Mining/Hephaestus/Hephaestus2.dmm
  _maps/map_files/PVP/Hulk.dmm
  _maps/map_files/Pegasus/pegasus1.dmm
  _maps/map_files/Tycoon/Tycoon1.dmm
  _maps/map_files/Tycoon/Tycoon2.dmm
  _maps/map_files/Vago/vagodeck1.dmm
  _maps/map_files/jollysausage/todger.dmm
  _maps/map_files/missileboat/combined_dev.dmm
  code/modules/reagents/reagent_dispenser.dm
  nsv13/code/modules/cargo/packs.dm
  nsv13/code/modules/munitions/ammunition/cannon_ammo.dm
  nsv13/code/modules/munitions/ammunition/countermeasure_ammo.dm
  nsv13/code/modules/munitions/ammunition/gauss_ammo.dm
  nsv13/code/modules/munitions/ammunition/pdc_ammo.dm
  nsv13/code/modules/munitions/ammunition/railgun_ammo.dm
  nsv13/code/modules/munitions/ammunition/torpedos/torpedo_construction.dm
  nsv13/code/modules/munitions/ammunition/torpedos/torpedo_parts.dm
  nsv13/code/modules/munitions/ammunition/torpedos/torpedo_types.dm
  nsv13/code/modules/munitions/munitions_trolley.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/deck_guns.dm
  nsv13/code/modules/overmap/ai-skynet2.dm
  nsv13/code/modules/overmap/armour/nano_pump.dm
  nsv13/code/modules/overmap/armour/nano_well.dm
  nsv13/code/modules/overmap/fighters/construction.dm
  nsv13/code/modules/overmap/fighters/control_console.dm
  nsv13/code/modules/overmap/fighters/fighters2.dm
  nsv13/code/modules/overmap/fighters/fighters_launcher.dm
  nsv13/code/modules/overmap/fighters/fuel_tank.dm
  nsv13/code/modules/overmap/fighters/tug.dm
  nsv13/code/modules/overmap/ftl.dm
  nsv13/code/modules/overmap/hull_plating.dm
  nsv13/code/modules/overmap/overmap.dm
  nsv13/code/modules/overmap/radar.dm
  nsv13/code/modules/overmap/shieldgen.dm
  nsv13/code/modules/overmap/starmap.dm
  nsv13/code/modules/overmap/traders.dm
  nsv13/code/modules/overmap/weapons/projectiles_fx.dm
  nsv13/code/modules/power/reactor/control_rods.dm
  nsv13/code/modules/power/reactor/rbmk.dm
  nsv13/code/modules/power/stormdrive.dm
  nsv13/code/modules/reagents/chemistry/recipes.dm
  nsv13/icons/obj/objects.dmi
  tgui/packages/tgui/interfaces/AviationFuel.js
  tgui/packages/tgui/interfaces/Dradis.js
  tgui/public/tgui.bundle.js
Labels: Code Improvement, Fix, Map Edit, Needs Test Merge, Refactor, TGUI-Changes, UI, mapping

#1437 apnp/w + pdsr tweaks
  nsv13/code/modules/overmap/armour/nano_pump.dm
  nsv13/code/modules/overmap/armour/nano_well.dm
  nsv13/code/modules/overmap/pdsr.dm
  nsv13/code/modules/power/stormdrive.dm
  tgui/packages/tgui/interfaces/ArmourPlatingNanorepairWell.js
  tgui/public/tgui.bundle.js
Labels: TGUI-Changes

#1383 Optimizes shares_overmap()
  nsv13/code/__HELPERS/overmap.dm
  nsv13/code/modules/power/reactor/rbmk.dm
Labels: Code Improvement

#1431 Fixes shipweapon hitboxes, and other shipweapon things
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/deck_guns.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/gauss_gun.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/torpedo_launcher.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/torpedo_launcher_construction.dm
Labels: Fix, Tweak

#1424 Fixes dradis consoles sometimes getting stuck at active sensor range
  nsv13/code/modules/overmap/radar.dm
Labels: Fix

#1386 Fixes Eclipse's research servers
  _maps/map_files/Eclipse/Eclipse1.dmm
Labels: Active Test Merge, mapping

#1418 [TESTMERGE-READY] Multi-Z improvements
  code/game/atoms_movable.dm
  code/game/objects/structures/stairs.dm
  code/game/turfs/turf.dm
  code/modules/mob/living/living.dm
  code/modules/vehicles/ridden.dm
Labels: Active Test Merge, Fix, Multi-Z, Needs Test Merge

#1459 More Stairs
  code/game/objects/structures/stairs.dm
Labels: Fix, Tweak

#1415 Revert cult to pre bee nerf state
  code/modules/antagonists/cult/blood_magic.dm
  code/modules/antagonists/cult/cult_items.dm
Labels: Active Test Merge, Balance/Rebalance, Tweak

#1454 Monotiles as plating and plated catwalk fixes
  code/game/objects/structures/catwalk.dm
  code/game/turfs/open/floor/plating.dm
  code/game/turfs/open/openspace.dm
  code/game/turfs/open/space/space.dm
  nsv13/code/game/objects/structures/catwalk.dm
Labels: Active Test Merge, Fix, Tweak

#1464 Fixes the Cryofuel UI
  tgui/packages/tgui/interfaces/CryogenicFuel.js
  tgui/public/tgui.bundle.js
Labels: TGUI-Changes

#1364 Legacy file cleaning
  nsv13.dme
  nsv13/code/modules/overmap/ai-skynet.dm
  nsv13/code/modules/overmap/ai-skynet2.dm
  nsv13/code/modules/overmap/fighters/_fighters.dm
  nsv13/code/modules/overmap/weapons.dm
  nsv13/code/modules/overmap/weapons/weapons.dm
Labels: Code Improvement

#1489 Makes PDC do the BRRT again
  nsv13.dme
  nsv13/code/datums/weapon_types.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/50Cal.dm
Labels: Active Test Merge, Balance/Rebalance, Passed Test Merge, Sound

#1492 Bambi 2 Armours 2 VHS 2-sided
  nsv13/code/modules/overmap/types/nanotrasen.dm
  nsv13/code/modules/overmap/types/solgov.dm
  nsv13/code/modules/overmap/types/spacepirates.dm
  nsv13/code/modules/overmap/types/syndicate.dm
Labels: Active Test Merge, Balance/Rebalance, Passed Test Merge

#1491 Fixes a multi-z disposal runtime
  code/modules/recycling/disposal/holder.dm
Labels: Fix, Runtime

#1484 Tweaks cannon ammo text
  nsv13/code/modules/munitions/ammunition/cannon_ammo.dm
Labels: Grammar and Formatting

#1507 Updates codeowners
  .github/CODEOWNERS
Labels: GitHub
