Repository BeeStation/NSV13, pull requests merged in 2021-01, with the labels that each got.

#1160 Adds Munitions (Orange) colored turf decals for mapping
  nsv13/game/custom_turfs.dm
Labels: Feature

#1161 Asteroid fixes
  _maps/map_files/Mining/nsv13/ruins/mining10.dmm
  _maps/map_files/Mining/nsv13/ruins/mining11.dmm
  _maps/map_files/Mining/nsv13/ruins/mining12.dmm
  _maps/map_files/Mining/nsv13/ruins/mining13.dmm
  _maps/map_files/Mining/nsv13/ruins/mining14.dmm
  _maps/map_files/Mining/nsv13/ruins/mining15.dmm
  _maps/map_files/Mining/nsv13/ruins/mining16.dmm
  _maps/map_files/Mining/nsv13/ruins/mining17.dmm
  _maps/map_files/Mining/nsv13/ruins/mining18.dmm
  _maps/map_files/Mining/nsv13/ruins/mining19.dmm
  _maps/map_files/Mining/nsv13/ruins/mining20.dmm
  _maps/map_files/Mining/nsv13/ruins/mining21.dmm
  _maps/map_files/Mining/nsv13/ruins/mining22.dmm
  _maps/map_files/Mining/nsv13/ruins/mining23.dmm
  _maps/map_files/Mining/nsv13/ruins/mining24.dmm
  _maps/map_files/Mining/nsv13/ruins/mining25.dmm
  _maps/map_files/Mining/nsv13/ruins/mining26.dmm
  _maps/map_files/Mining/nsv13/ruins/mining27.dmm
  _maps/map_files/Mining/nsv13/ruins/mining28.dmm
  _maps/map_files/Mining/nsv13/ruins/mining29.dmm
  _maps/map_files/Mining/nsv13/ruins/mining30.dmm
  _maps/map_files/Mining/nsv13/ruins/mining7.dmm
  _maps/map_files/Mining/nsv13/ruins/mining8.dmm
  _maps/map_files/Mining/nsv13/ruins/mining9.dmm
Labels: Feature, Fix, Map Edit

#1167 Allows creation of missile builders
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/revision2/automation.dm
Labels: Fix

#1163 Fix slow conveyors
  code/modules/recycling/conveyor2.dm
  nsv13/code/modules/munitions/ammunition/torpedos/torpedo_parts.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/revision2/automation.dm
Labels: Feature

#1173 Adds guidance computer bolt driver to gladius missile factory
  _maps/map_files/Gladius/Gladius1.dmm
Labels: Fix, Map Edit

#1149 ports ethereal qol and fixes lights not using power from ethereal draining
  code/modules/mob/living/carbon/human/human.dm
  code/modules/power/apc.dm
  code/modules/power/lighting.dm
Labels: Fix, Tweak

#1175 Makes it impossible to pick up munitions ammo with an evidence bag and gives cannonballs a construction time
  code/game/objects/items/stacks/sheets/sheet_types.dm
  nsv13/code/modules/munitions/ammunition/missiles/missile_types.dm
  nsv13/code/modules/munitions/ammunition/torpedos/torpedo_types.dm
  nsv13/code/modules/munitions/ship_weapons/_ship_weapon.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/deck_guns.dm
Labels: Balance/Rebalance, Fix, Priority: High

#1143 Makes it so fighter pilot armor is no longer the second strongest armor you can get.
  nsv13/code/modules/clothing/custom_clothes.dm
Labels: Balance/Rebalance

#1179 Gladius Atmos Changes
  _maps/map_files/Gladius/Gladius2.dmm
Labels: Active Test Merge, Feature, Map Edit, Removal, Tweak

#1186 fixed missile construction not finishing
  nsv13/code/modules/munitions/ammunition/missiles/missile_construction.dm
Labels: Fix

#1191 Some breach fixing stuff
  code/game/objects/effects/effect_system/effects_foam.dm
  nsv13/code/modules/overmap/components.dm
Labels: Fix, Tweak

#1183 Minor APNP/W Tweaks
  nsv13/code/modules/overmap/armour/nano_pump.dm
  nsv13/code/modules/overmap/armour/nano_well.dm
  tgui/packages/tgui/interfaces/ArmourPlatingNanorepairWell.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Active Test Merge, Balance/Rebalance, UI

#1131 Improves the RCL by making it a radial dial selection of kinds of wires
  _maps/map_files/Aetherwhisp/Aetherwhisp1.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Donutstation/Donutstation.dmm
  _maps/map_files/Eclipse/Eclipse.dmm
  _maps/map_files/Gladius/Gladius2.dmm
  _maps/map_files/Hammerhead/Hammerhead.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/NSV Storage/Mining/Hephaestus/Hephaestus1.dmm
  _maps/map_files/Pegasus/pegasus1.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/Tycoon/Tycoon2.dmm
  code/datums/components/crafting/recipes.dm
  code/game/objects/items/RCL.dm
  code/game/turfs/turf.dm
  code/modules/power/cable.dm
  code/modules/research/designs/tool_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Active Test Merge, Map Edit, Tweak

#1198 Makes the goose drop meat that's not invisible
  code/modules/mob/living/simple_animal/hostile/goose.dm
Labels: Fix

#1171 Updates Rocinante for newnitions
  _maps/map_files/Mining/nsv13/Rocinante.dmm
Labels: Balance/Rebalance, Fix, Map Edit, Removal

#1196 Books work, config updated
  code/game/objects/items/manuals.dm
  icons/obj/nsv_bureaucracy.dmi
Labels: Config Update, Feature, Fix, Sprites

#1170 Fixes some issues on the Tycoon
  _maps/map_files/Tycoon/Tycoon1.dmm
  _maps/map_files/Tycoon/Tycoon2.dmm
Labels: Active Test Merge, Fix, Map Edit, Work In Progress

#1207 Adds a Munitions Techfab and makes FTL nav console buildable
  _maps/map_files/Gladius/Gladius1.dmm
  _maps/map_files/Jeppison/Jeppison2.dmm
  _maps/map_files/Tycoon/Tycoon2.dmm
  code/__DEFINES/research.dm
  nsv13.dme
  nsv13/code/game/machinery/munitions_machinery.dm
  nsv13/code/modules/munitions/ammunition/countermeasure_ammo.dm
  nsv13/code/modules/munitions/ammunition/torpedos/torpedo_parts.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/50Cal.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/revision2/automation.dm
  nsv13/code/modules/munitions/ship_weapons/energy_weapons/phaser.dm
  nsv13/code/modules/munitions/ship_weapons/ship_weapon_research.dm
  nsv13/code/modules/overmap/components.dm
  nsv13/code/modules/overmap/fighters/construction.dm
  nsv13/code/modules/overmap/fighters/control_console.dm
  nsv13/code/modules/overmap/fighters/fighters_launcher.dm
  nsv13/code/modules/overmap/ftl.dm
  nsv13/code/modules/overmap/radar.dm
  nsv13/code/modules/overmap/starmap.dm
  nsv13/code/modules/research/machinery/departmental_protolathe.dm
Labels: Feature, Map Edit, Tweak

#1180 [Map update] Eclipse newnitions upgrade.
  _maps/Eclipse.dm
  _maps/_basemap.dm
  _maps/eclipse.json
  _maps/map_files/Eclipse/Eclipse1.dmm
  _maps/map_files/Eclipse/Eclipse2.dmm
  nsv13/code/modules/overmap/types/nanotrasen.dm
  nsv13/game/custom_turfs.dm
Labels: Active Test Merge, Code Improvement, Feature, Map Edit, Removal, Tweak

#1211 cleaning up debug tests
  _maps/map_files/Eclipse/Eclipse1.dmm
Labels: Map Edit

#1202 SOP book update (but more of a chad)
  code/game/objects/items/manuals.dm
  icons/obj/nsv_bureaucracy.dmi
  nsv13/icons/obj/nsv_bureaucracy.dmi
Labels: Sprites, Tweak

#1209 Jerry ate the cheese
  code/modules/atmospherics/environmental/LINDA_turf_tile.dm
Labels: Active Test Merge, Needs Test Merge

#1203 Volatility Calibrations - WIP
  nsv13/code/modules/munitions/ship_weapons/volatility_component.dm
Labels: Active Test Merge, Balance/Rebalance

#1162 Pirates
  _maps/templates/pirate_pod.dmm
  code/__DEFINES/radio.dm
  code/controllers/subsystem/blackbox.dm
  code/game/communications.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/say.dm
  code/modules/events/pirates.dm
  code/modules/goonchat/browserassets/css/browserOutput.css
  code/modules/goonchat/browserassets/css/browserOutput_white.css
  code/modules/mining/machine_bluespaceminer.dm
  code/modules/mob/living/say.dm
  interface/stylesheet.dm
  nsv13.dme
  nsv13/code/controllers/subsystem/starsystem.dm
  nsv13/code/game/objects/items/space_pirate_items.dm
  nsv13/code/modules/clothing/custom_outfits.dm
  nsv13/code/modules/overmap/ai-skynet2.dm
  nsv13/code/modules/overmap/boarding/boarding.dm
  nsv13/code/modules/overmap/factions.dm
  nsv13/code/modules/overmap/fighters/fighters2.dm
  nsv13/code/modules/overmap/types/spacepirates.dm
  nsv13/code/modules/power/stormdrive.dm
  nsv13/icons/mob/head.dmi
  nsv13/icons/mob/suit.dmi
  nsv13/icons/obj/clothing/hats.dmi
  nsv13/icons/obj/clothing/suits.dmi
  nsv13/icons/obj/custom_radio.dmi
  nsv13/icons/overmap/new/nanotrasen/frigate.dmi
  nsv13/icons/overmap/syndicate/gunboat.dmi
  nsv13/icons/overmap/syndicate/syn_light_cruiser.dmi
Labels: Active Test Merge, Config Update, Map Edit, Sprites, UI

#1218 About smart fleets and hidden systems
  nsv13/code/modules/overmap/ai-skynet2.dm
  nsv13/code/modules/overmap/fleet_ftl_pathfinding.dm
Labels: Tweak
