Repository BeeStation/NSV13, pull requests merged in 2021-05, with the labels that each got.

#1408 Probably fixes munitions trolleys
  nsv13/code/modules/munitions/munitions_trolley.dm
Labels: Active Test Merge, Fix, Priority: High

#1361 Ethereal Blood [Ready]
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/recipes/medicine.dm
Labels: Feature, Needs Review

#1368 [Experimental] Lowpop PVP!
  _maps/map_files/Instanced/astraeusPVP.json
  _maps/map_files/Instanced/hammurabiPVP.json
  _maps/map_files/Instanced/map_files/Babylon1.dmm
  _maps/map_files/Instanced/map_files/Babylon2.dmm
  _maps/map_files/Instanced/map_files/SpaceSHIP.dmm
  _maps/map_files/Mining/nsv13/Rook.dmm
  _maps/map_files/PVP/Hammurabi1.dmm
  _maps/map_files/PVP/Hammurabi2.dmm
  code/__HELPERS/type2type.dm
  nsv13.dme
  nsv13/code/datums/shuttles.dm
  nsv13/code/game/area/areas.dm
  nsv13/code/game/area/hammurabi.dm
  nsv13/code/game/gamemodes/pvp/pvp.dm
  nsv13/code/game/gamemodes/pvp/roles.dm
  nsv13/code/game/machinery/custom_machines.dm
  nsv13/code/game/objects/items/nsv_circuitboards.dm
  nsv13/code/modules/clothing/custom_clothes.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/gauss_gun.dm
  nsv13/code/modules/overmap/ftl.dm
  nsv13/code/modules/turbolift/lazylift.dm
Labels: Feature, Fix, Map Edit, mapping

#1393 [Ready] Airlocks
  code/game/machinery/doors/airlock.dm
  nsv13/code/game/machinery/custom_airlocks.dm
  nsv13/goonstation/icons/airlock_glass.dmi
  nsv13/goonstation/icons/command.dmi
  nsv13/goonstation/icons/command_glass.dmi
  nsv13/goonstation/icons/engineering.dmi
  nsv13/goonstation/icons/engineering_glass.dmi
  nsv13/goonstation/icons/external.dmi
  nsv13/goonstation/icons/external_glass.dmi
  nsv13/goonstation/icons/maintenance.dmi
  nsv13/goonstation/icons/medical.dmi
  nsv13/goonstation/icons/public.dmi
  nsv13/goonstation/icons/security.dmi
  nsv13/icons/obj/machinery/doors/hatch.dmi
  nsv13/icons/obj/machinery/doors/overlays.dmi
  nsv13/icons/obj/machinery/doors/overlays/overlays.dmi
  nsv13/icons/obj/machinery/doors/overlays/overlays_external.dmi
  nsv13/icons/obj/machinery/doors/overlays/overlays_goon.dmi
  nsv13/icons/obj/machinery/doors/overlays/overlays_goon_glass.dmi
  nsv13/icons/obj/machinery/doors/overlays/overlays_hatch.dmi
  nsv13/icons/obj/machinery/doors/overlays/overlays_large.dmi
  nsv13/icons/obj/machinery/doors/overlays/overlays_standard.dmi
  nsv13/icons/obj/machinery/doors/overlays/overlays_vault.dmi
  nsv13/icons/obj/machinery/doors/secure.dmi
  nsv13/icons/obj/machinery/doors/standard.dmi
  nsv13/icons/obj/machinery/doors/station.dmi
  nsv13/icons/obj/machinery/doors/station_glass.dmi
  nsv13/icons/obj/machinery/doors/vault.dmi
Labels: Active Test Merge, Code Improvement, Fix, Sprites

#1404 Fixes Ship-to-Ship Repairs
  nsv13/code/modules/overmap/ai-skynet2.dm
Labels: Fix, Passed Test Merge, Tweak

#1417 fixes fighter part sprites
  nsv13/code/modules/overmap/fighters/construction.dm
  nsv13/code/modules/overmap/fighters/fighters2.dm
Labels: Fix

#1406 Fix for Spacepirate PDC not firing
  nsv13/code/modules/overmap/types/spacepirates.dm
Labels: Fix

#1400 Fixed thorny spacevine interactions
  code/modules/events/spacevine.dm
Labels: Fix

#1414 Makes Duranium walls require a reinforced girder to be built
  nsv13/code/game/turfs/custom_turfs.dm
Labels: Balance/Rebalance

#1401 Makes unanchored windows and falsewalls show up
  code/game/objects/structures/girders.dm
  nsv13.dme
  nsv13/code/game/objects/structures/railing.dm
  nsv13/code/game/turfs/custom_decals.dm
  nsv13/code/game/turfs/custom_floors.dm
  nsv13/code/game/turfs/custom_signs.dm
  nsv13/code/game/turfs/custom_turfs.dm
  nsv13/code/game/turfs/legacy_smooth.dm
  nsv13/code/game/turfs/wall.dm
  nsv13/code/game/turfs/window.dm
  nsv13/icons/turf/interior_wall.dmi
  nsv13/icons/turf/reinforced_wall.dmi
  nsv13/icons/turf/wall_masks.dmi
Labels: Code Improvement, Fix, Sprites

#1388 Adds kamikaze headband
  nsv13/code/game/machinery/munitions_machinery.dm
  nsv13/code/modules/clothing/custom_clothes.dm
  nsv13/icons/mob/head.dmi
  nsv13/icons/obj/clothing/hats.dmi
Labels: Feature, Sprites

#1382 try_use_power()
  nsv13/code/modules/overmap/armour/nano_well.dm
  nsv13/code/modules/overmap/shieldgen.dm
Labels: Code Improvement

#1387 Fixes fighter pilots suffocating in pressurized areas without a canopy
  nsv13/code/modules/overmap/fighters/fighters2.dm
  nsv13/code/modules/overmap/overmap.dm
Labels: Fix, Passed Test Merge
