Repository BeeStation/NSV13, pull requests merged in 2021-04, with the labels that each got.

#1236 MAA bombsuit
  nsv13/code/game/machinery/munitions_machinery.dm
  nsv13/code/modules/clothing/custom_clothes.dm
  nsv13/icons/mob/head.dmi
  nsv13/icons/mob/suit.dmi
  nsv13/icons/obj/clothing/hats.dmi
  nsv13/icons/obj/clothing/suits.dmi
Labels: Feature, Mass Map Change, Sprites

#1319 Gauss Projectile Resprite
  icons/obj/projectiles.dmi
Labels: Active Test Merge, Sprites, Tweak

#1318 50cal and naval loader feedback, autogauss recipe filepath fix
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/50Cal.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/deck_guns.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/gauss_gun.dm
Labels: Active Test Merge, Feature, Fix

#1305 Tweaks to size scaling & some more
  nsv13/code/controllers/subsystem/starsystem.dm
  nsv13/code/modules/overmap/ai-skynet2.dm
Labels: Active Test Merge, Balance/Rebalance, Code Improvement, Fix, Removal

#1325 Fixes a runtime that causes the CI to scream
  nsv13/code/_HELPERS/overmap.dm
Labels: Fix

#1334 Fixes AI up/down buttons
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/ai.dm
  nsv13/code/_onclick/hud/ai.dm
  nsv13/code/modules/overmap/overmap.dm
Labels: Active Test Merge, Fix

#1343 Increases maximum TGUI windows and timeout for opening windows
  code/__DEFINES/tgui.dm
Labels: Active Test Merge, Tweak

#1324 April fools is literally bricking the job selection this is funny but also really isn't
  code/modules/holiday/holidays.dm
Labels: Active Test Merge, Fix

#1331 Fixes some things I guess
  code/game/machinery/recycler.dm
  code/modules/clothing/under/costume.dm
  nsv13/code/game/machinery/computer/munitions.dm
  nsv13/code/game/objects/structures/custom_closets.dm
  nsv13/code/modules/cargo/packs.dm
  nsv13/code/modules/clothing/custom_clothes.dm
  nsv13/code/modules/jobs/security/weapons.dm
  nsv13/code/modules/munitions/ammunition/torpedos/torpedo_parts.dm
  nsv13/code/modules/overmap/armour/nano_pump.dm
  nsv13/code/modules/overmap/armour/nano_well.dm
  nsv13/code/modules/research/astrometrics.dm
  nsv13/code/modules/research/designs/munitions_designs.dm
  nsv13/code/modules/research/designs/ship_weapon_designs.dm
Labels: Active Test Merge, Code Improvement, Feature, Fix, Removal, Tweak

#1337 Gave brigphys access to brig
  code/modules/jobs/job_types/brigphys.dm
Labels: Active Test Merge, Fix

#1332 Resolves some airlock and parallax issues from the rebase
  code/_onclick/hud/parallax.dm
  code/game/machinery/doors/airlock.dm
  nsv13/code/game/machinery/custom_airlocks.dm
Labels: Active Test Merge, Fix

#1299 NSV13 clown specific sub sprites are renamed. Updated all pathing
  nsv13/code/modules/clothing/custom_clothes.dm
  nsv13/icons/mob/feet.dmi
  nsv13/icons/mob/suit.dmi
  nsv13/icons/mob/uniform.dmi
  nsv13/icons/obj/clothing/shoes.dmi
  nsv13/icons/obj/clothing/suits.dmi
  nsv13/icons/obj/clothing/uniforms.dmi
Labels: Active Test Merge, Fix

#1355 Fixes Radstorms triggering like crazy
  nsv13/code/controllers/subsystem/starsystem.dm
Labels: Fix

#1342 Allowed AI to see the AI multicam room and the Overmap
  code/modules/mob/living/silicon/ai/freelook/cameranet.dm
Labels: Active Test Merge, Fix

#1340 Adds captain's spare safe to Tycoon
  _maps/map_files/Tycoon/Tycoon2.dmm
Labels: Feature, Map Edit, mapping

#1330 NPC Hitbox Expansion
  nsv13/code/modules/overmap/types/spacepirates.dm
  nsv13/code/modules/overmap/types/syndicate.dm
Labels: Active Test Merge

#1347 Returns contents_explosions validity checking to pre-beebase state and fixes FTL computers getting bricked due to same-tile explosions
  code/__DEFINES/flags.dm
  code/_globalvars/bitfields.dm
  code/controllers/subsystem/explosion.dm
  nsv13/code/modules/overmap/ftl.dm
Labels: Code Improvement, Fix

#1329 Fixes supermatter starting at 1 power
  code/modules/power/supermatter/supermatter.dm
Labels: Fix

#1366 More bee fixes
  code/controllers/subsystem/job.dm
  code/controllers/subsystem/tgui.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  nsv13/code/modules/mining/asteroid.dm
Labels: Feature, Fix, Tweak, enhancement

#1365 Bug fixes and minor optimizations
  nsv13/code/modules/mining/asteroid.dm
  nsv13/code/modules/munitions/ship_weapons/_ship_weapon.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/50Cal.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/deck_guns.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/pdc.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/pdc_construction.dm
  nsv13/code/modules/overmap/physics.dm
  nsv13/code/modules/overmap/physics2d.dm
  nsv13/code/modules/power/rbmk.dm
  nsv13/code/modules/power/stormdrive.dm
  nsv13/code/modules/vehicles/hardpoint.dm
Labels: Code Improvement, Fix

#1363 Deckgun QOL improvement
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/deck_guns.dm
  tgui/packages/tgui/interfaces/DeckGun.js
  tgui/public/tgui.bundle.js
Labels: Fix, TGUI-Changes, Tweak, UI

#1372 Makes clown jacket visible again.
  nsv13/icons/mob/suit.dmi
  nsv13/icons/obj/clothing/suits.dmi
Labels: Fix

#1289 [READY] [ANTAG] IT CAME FROM OUTER SPACE....
  _maps/map_files/Atlas/atlas.dmm
  _maps/map_files/Atlas/atlas2.dmm
  code/__DEFINES/atom_hud.dm
  code/__DEFINES/nsv13.dm
  code/__DEFINES/role_preferences.dm
  code/game/machinery/doors/door.dm
  code/modules/antagonists/blob/overmind.dm
  code/modules/antagonists/changeling/changeling.dm
  code/modules/antagonists/changeling/powers/headcrab.dm
  code/modules/antagonists/changeling/powers/hivemind.dm
  code/modules/mob/living/carbon/alien/larva/powers.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/simple_animal/eldritch_demons.dm
  html/antagtips/bloodling.html
  html/antagtips/bloodling_thrall.html
  icons/mob/hud.dmi
  icons/title_cards.dmi
  nsv13.dme
  nsv13/code/game/gamemodes/bloodling.dm
  nsv13/code/game/general_quarters/squad.dm
  nsv13/code/game/general_quarters/squad_items.dm
  nsv13/code/game/general_quarters/squad_management.dm
  nsv13/code/modules/antagonists/bloodling.dm
  nsv13/code/modules/antagonists/simple_teamchat.dm
  nsv13/icons/mob/actions/actions_bloodling.dmi
  nsv13/icons/mob/actions/actions_teamchat.dmi
  nsv13/icons/mob/bloodling.dmi
  nsv13/sound/effects/bloodling_absorb.ogg
  nsv13/sound/effects/bloodling_awaken.ogg
  nsv13/sound/effects/bloodling_squelch.ogg
  nsv13/sound/effects/radiostatic.ogg
Labels: Active Test Merge, Feature, Map Edit, Needs Review, Roadmap, Sprites, mapping

#1362 Gunpowder loading on munitions trolley
  nsv13/code/modules/munitions/munitions_trolley.dm
Labels: Code Improvement, Feature

#1371 Adds a wall to the Atlas arrivals shuttle to prevent felenids from being deafened
  _maps/shuttles/arrival_atlas.dmm
Labels: Active Test Merge, Map Edit, mapping

#1373 Fixes atmosmachine rotation
  code/modules/atmospherics/machinery/atmosmachinery.dm
Labels: Fix

#1370 Advanced reactor fuel rods port
  nsv13.dme
  nsv13/code/modules/cargo/exports/engineering.dm
  nsv13/code/modules/power/reactor/control_rods.dm
  nsv13/code/modules/power/reactor/fuel_rods.dm
  nsv13/code/modules/power/reactor/rbmk.dm
  nsv13/code/modules/uplink/uplink_items.dm
Labels: Active Test Merge, Feature, Tweak

#1374 Fixes/Cleans defines and helpers
  nsv13.dme
  nsv13/code/__DEFINES/components.dm
  nsv13/code/__DEFINES/fleets.dm
  nsv13/code/__DEFINES/localisation/_localisation.dm
  nsv13/code/__DEFINES/localisation/localisation_de.dm
  nsv13/code/__DEFINES/localisation/localisation_fr.dm
  nsv13/code/__DEFINES/localisation/localisation_ru.dm
  nsv13/code/__DEFINES/medal.dm
  nsv13/code/__DEFINES/missions.dm
  nsv13/code/__DEFINES/overmap.dm
  nsv13/code/__DEFINES/research.dm
  nsv13/code/__DEFINES/ships.dm
  nsv13/code/__HELPERS/maths.dm
  nsv13/code/__HELPERS/matrices.dm
  nsv13/code/__HELPERS/overmap.dm
  nsv13/code/modules/mapping/space_management/space_level.dm
  nsv13/code/modules/mob/dead/observer/oberserver.dm
  nsv13/code/modules/mob/mob.dm
  nsv13/code/modules/research/designs/tool_designs.dm
Labels: Code Improvement, Refactor

#1384 Munitions trolley fixes and code improvements
  nsv13/code/modules/munitions/munitions_trolley.dm
Labels: Fix

#1333 Adds a hull foam extinguisher for mechs
  code/game/mecha/equipment/tools/work_tools.dm
  code/modules/research/techweb/all_nodes.dm
  nsv13/code/modules/research/designs/mechfabricator_designs.dm
Labels: Active Test Merge, Code Improvement, Feature

#1380 Re-adds our fancy FTL parallax and more!
  code/_onclick/hud/parallax.dm
  nsv13/code/_onclick/hud/parallax.dm
Labels: Feature

#1377 Throttles SSambience.
  code/controllers/subsystem/ambience.dm
  code/modules/client/client_defines.dm
  code/modules/tgui_panel/audio.dm
Labels: Active Test Merge, Tweak

#1369 [Ready] Gladius Update
  _maps/map_files/Gladius/Gladius1.dmm
  _maps/map_files/Gladius/Gladius2.dmm
  _maps/shuttles/cargo_gladius.dmm
Labels: Active Test Merge, Map Edit, Needs Review, Tweak, mapping

#1367 [NOT WIP] Genpop take 2!
  _maps/map_files/Atlas/atlas.dmm
  _maps/map_files/Atlas/atlas2.dmm
  _maps/map_files/Gladius/Gladius1.dmm
  _maps/map_files/Testship/testship.dmm
  _maps/map_files/Tycoon/Tycoon1.dmm
  _maps/map_files/Tycoon/Tycoon2.dmm
  _maps/shuttles/emergency_atlas.dmm
  code/__DEFINES/access.dm
  nsv13.dme
  nsv13/code/game/gamemodes/bloodling.dm
  nsv13/code/modules/Security/genpop.dm
  nsv13/code/modules/antagonists/bloodling.dm
  nsv13/icons/obj/objects.dmi
  nsv13/icons/obj/status_display.dmi
  tgui/packages/tgui/interfaces/GenPop.js
  tgui/public/tgui-common.chunk.js
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.js
Labels: Active Test Merge, Feature, Map Edit, TGUI-Changes, UI, mapping

#1356 Fix radio SFX playing twice
  code/game/objects/items/devices/radio/radio.dm
  nsv13/code/modules/antagonists/simple_teamchat.dm
  nsv13/sound/effects/radio1.ogg
  nsv13/sound/effects/radio2.ogg
Labels: Fix

#1381 Replace Atlas munitions protolathe with techfab
  _maps/map_files/Atlas/atlas.dmm
Labels: Fix, Map Edit, mapping
