Repository BeeStation/NSV13, pull requests merged in 2021-07, with the labels that each got.

#1498 Adds PDC spread and makes torpedos easier to kill
  nsv13/code/datums/weapon_types.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/50Cal.dm
  nsv13/code/modules/overmap/weapons/projectiles_fx.dm
Labels: Active Test Merge, Balance/Rebalance

#1462 Probably fixes Hammurabi Z-levels
  _maps/map_files/Instanced/hammurabiPVP.json
  _maps/map_files/PVP/Hammurabi1.dmm
  _maps/map_files/PVP/Hammurabi2.dmm
Labels: Active Test Merge, Passed Test Merge, mapping

#1458 Optionally ID-based lift buttons
  nsv13/code/modules/turbolift/lazylift.dm
Labels: Code Improvement, Multi-Z

#1508 Fixes a random physics runtime
  nsv13/code/modules/overmap/physics.dm
Labels: Fix, Runtime

#1479 Makes "Elite" ships slightly more scary
  code/__DEFINES/flags.dm
  code/_globalvars/bitfields.dm
  nsv13/code/__DEFINES/skynet.dm
  nsv13/code/datums/weapon_types.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/revision2/vls.dm
  nsv13/code/modules/overmap/ai-skynet.dm
  nsv13/code/modules/overmap/overmap.dm
  nsv13/code/modules/overmap/types/spacepirates.dm
  nsv13/code/modules/overmap/types/syndicate.dm
Labels: Ship/Physics, enhancement

#1518 Removes maps that are out of rotation from the code
  _maps/_basemap.dm
  _maps/destroyer.dm
  _maps/destroyer.json
  _maps/hammerhead.dm
  _maps/hammerhead.json
  _maps/jeppison.dm
  _maps/jeppison.json
  _maps/jollysausage.dm
  _maps/jollysausage.json
  _maps/map_files/Galactica/Galactica2.dmm
  _maps/map_files/Hammerhead/Hammerhead.dmm
  _maps/map_files/Instanced/hulkPVP.json
  _maps/map_files/Jeppison/Jeppison1.dmm
  _maps/map_files/Jeppison/Jeppison2.dmm
  _maps/map_files/Jeppison/job_changes.dm
  _maps/map_files/NSV Storage/aerwhisp_hull.dmm
  _maps/map_files/PVP/Hulk.dmm
  _maps/map_files/Pegasus/job_changes.dm
  _maps/map_files/Pegasus/pegasus1.dmm
  _maps/map_files/Pegasus/pegasus2.dmm
  _maps/map_files/jollysausage/job_changes.dm
  _maps/map_files/jollysausage/todger.dmm
  _maps/map_files/missileboat/combined_dev.dmm
  _maps/pegasus.dm
  _maps/pegasus.json
  code/modules/jobs/map_changes/map_changes.dm
Labels: Hammerhead, Mass Map Change, mapping

#1493 Rat Fix 2 : Disease boogaloo
  code/modules/awaymissions/corpse.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Active Test Merge, Fix

#1403 Bee-Legacy Engineering Uniforms and Hardsuit
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/under/jobs/engineering.dm
  nsv13/icons/mob/head.dmi
  nsv13/icons/mob/suit.dmi
  nsv13/icons/mob/uniform.dmi
  nsv13/icons/obj/clothing/hats.dmi
  nsv13/icons/obj/clothing/suits.dmi
  nsv13/icons/obj/clothing/uniforms.dmi
Labels: Passed Test Merge, Revert, Sprites

#1391 Adds another repair thing for mechs and fixes some stuff not existing
  code/game/mecha/equipment/tools/work_tools.dm
  code/modules/research/techweb/all_nodes.dm
  nsv13.dme
  nsv13/code/game/mecha/weapons.dm
  nsv13/code/game/mecha/work_tools.dm
  nsv13/code/modules/research/designs/mechfabricator_designs.dm
Labels: Active Test Merge, Feature, Fix

#1516 Fixes fighter avionics not having a sprite
  nsv13/code/modules/overmap/fighters/_fighters.dm
Labels: Fix

#1466 Adds fun new radiation event
  nsv13.dme
  nsv13/code/controllers/subsystem/starsystem.dm
  nsv13/code/modules/events/weather/deadly_radiation_storm.dm
  nsv13/code/modules/events/weather/radioactive_sludge.dm
Labels: Active Test Merge, Passed Test Merge

#1476 Makes the BSA station goal just the regular BSA
  code/modules/station_goals/bsa.dm
Labels: Active Test Merge, Balance/Rebalance, Fix

#1509 The AI has learned circlestrafing, plus some other improvements
  nsv13/code/modules/overmap/ai-skynet.dm
Labels: Active Test Merge, Feature, Fix, Tweak, enhancement

#1528 Fixes life, the universe and everything (actually, just fixes armor)
  code/datums/armor.dm
Labels: FUCK, Fix

#1524 Makes superstructure crit explosion intensity vary depending on damage dealt to the ship.
  nsv13/code/modules/overmap/armour/armour_quadrant.dm
  nsv13/code/modules/overmap/ftl.dm
  nsv13/code/modules/overmap/weapons/damage.dm
Labels: Balance/Rebalance, Needs Test Merge

#1513 Fixes some door related things on Gladius
  _maps/map_files/Gladius/Gladius1.dmm
  _maps/map_files/Gladius/Gladius2.dmm
Labels: Active Test Merge, mapping

#1511 Fixed pirate systems in starmap
  tgui/packages/tgui/styles/components/Map.scss
  tgui/public/tgui.bundle.css
Labels: Needs Test Merge, TGUI-Changes

#1531 Fighter name consistincy issue
  nsv13/code/modules/overmap/fighters/_fighters.dm
Labels: Fix

#1538 Munitions trolley fix
  nsv13/code/modules/munitions/munitions_trolley.dm
Labels: Fix

#1487 Bambi 2: Disables weapon parts techweb, makes circuits indestructable
  nsv13/code/game/machinery/computer/munitions.dm
  nsv13/code/game/objects/items/nsv_circuitboards.dm
  nsv13/code/modules/munitions/ammunition/gauss_ammo.dm
  nsv13/code/modules/munitions/ship_weapons/_ship_weapon.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/deck_guns.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/gauss_gun.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/revision2/vls.dm
  nsv13/code/modules/munitions/ship_weapons/ship_weapon_parts.dm
  nsv13/code/modules/research/designs/ship_weapon_designs.dm
  nsv13/code/modules/research/techweb/all_nsv_nodes.dm
Labels: Active Test Merge, Balance/Rebalance, Munitions, Roadmap

#1481 Fixes infinite money caused by cheap crates
  code/modules/cargo/packs.dm
  nsv13/code/modules/cargo/packs.dm
Labels: Active Test Merge, Fix

#1523 Bambi 2: Ultimatum
  code/datums/armor.dm
  nsv13/code/game/general_quarters/damage.dm
  nsv13/code/game/general_quarters/dropship_types.dm
  nsv13/code/modules/mining/asteroid.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/50Cal.dm
  nsv13/code/modules/munitions/ship_weapons/energy_weapons/phaser.dm
  nsv13/code/modules/overmap/fighters/_fighters.dm
  nsv13/code/modules/overmap/types/miningships.dm
  nsv13/code/modules/overmap/types/nanotrasen.dm
  nsv13/code/modules/overmap/types/solgov.dm
  nsv13/code/modules/overmap/types/spacepirates.dm
  nsv13/code/modules/overmap/types/syndicate.dm
  nsv13/code/modules/overmap/weapons/projectiles_fx.dm
Labels: Active Test Merge, Balance/Rebalance, Munitions

#1515 Makes trader stations immediately stop processing if they are created in a non-loaded system
  nsv13/code/modules/overmap/traders_items.dm
Labels: Active Test Merge, Starsystem, enhancement

#1525 Some fun comsig stuff
  code/__DEFINES/components.dm
  nsv13.dme
  nsv13/code/modules/overmap/ai-skynet.dm
  nsv13/code/modules/overmap/ftl.dm
  nsv13/code/modules/overmap/interdiction.dm
  nsv13/code/modules/overmap/types/syndicate.dm
  nsv13/icons/overmap/syndicate/syn_light_cruiser.dmi
Labels: Active Test Merge, Overmap, enhancement

#1537 Plutonium Sludge Placement is more reasonable
  nsv13.dme
  nsv13/code/game/objects/effects/custom_landmarks.dm
  nsv13/code/game/objects/effects/decals/plutonium_sludge.dm
  nsv13/code/modules/power/stormdrive.dm
Labels: Fix, Passed Test Merge

#1534 Lets you drag crates with missile parts into missile assembly part attachers
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/revision2/automation.dm
Labels: Active Test Merge, Munitions, enhancement

#1545 Stops Github Actions from closing stale issues after 180 days
  .github/workflows/stale_issues.yml
Labels: GitHub

#1550 Multiple Tycoon Fixes
  _maps/map_files/Tycoon/Tycoon1.dmm
  _maps/map_files/Tycoon/Tycoon2.dmm
Labels: mapping

#1549 Fixing a typo in the github stale issue notification
  .github/workflows/stale_issues.yml
Labels: GitHub

#1497 Adds ability for AI to lead targets
  nsv13/code/modules/overmap/ai-skynet.dm
  nsv13/code/modules/overmap/fighters/_fighters.dm
  nsv13/code/modules/overmap/overmap.dm
  nsv13/code/modules/overmap/physics.dm
  nsv13/code/modules/overmap/weapons/ship_weapon.dm
  nsv13/code/modules/overmap/weapons/weapons.dm
Labels: Active Test Merge, Code Improvement, Feature, Overmap, Ship/Physics, enhancement

#1504 Adds a mining trader
  nsv13/code/modules/overmap/traders.dm
  nsv13/code/modules/overmap/traders_items.dm
Labels: Active Test Merge, Overmap, Starsystem, enhancement

#1539 Boarding Cleanup
  _maps/map_files/Atlas/job_changes.dm
  _maps/map_files/Eclipse/job_changes.dm
  code/__DEFINES/atom_hud.dm
  code/datums/hud.dm
  code/game/data_huds.dm
  code/modules/clothing/glasses/hud.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  icons/mob/hud.dmi
  nsv13/code/game/general_quarters/squad.dm
  nsv13/code/game/general_quarters/squad2.dm
  nsv13/code/game/machinery/computer/salvage.dm
  nsv13/code/game/turfs/legacy_smooth.dm
  nsv13/code/modules/jobs/job_types/pilot.dm
Labels: Active Test Merge, Code Improvement, Fix, Sprites

#1556 Makes advanced tools yellow again
  icons/mob/inhands/equipment/tools_lefthand.dmi
  icons/mob/inhands/equipment/tools_righthand.dmi
  icons/obj/tools.dmi
Labels: Needs Test Merge, Sprites

#1536 Cleans up torp code
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/flak.dm
  nsv13/code/modules/overmap/weapons/projectiles_fx.dm
Labels: Fix, Munitions, Needs Test Merge, Refactor, enhancement
