Repository BeeStation/NSV13, pull requests merged in 2022-11, with the labels that each got.

#2107 Nerfs the alien infestation event
  code/modules/events/alien_infestation.dm
Labels: Balance/Rebalance, Active Test Merge, hacktoberfest-accepted

#2071 Allows Bridge RC on Eclipse to send announcements
  _maps/map_files/Eclipse/Eclipse1.dmm
Labels: Tweak, Active Test Merge, mapping, Eclipse

#2124 Fixes ammo sorters on Shrike having too little capacity
  _maps/map_files/Shrike/Shrike2.dmm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/revision2/automation.dm
Labels: Fix, Active Test Merge, mapping, Shrike

#2152 Adds safety checks for overmap vector overlays
  nsv13/code/modules/overmap/physics.dm
Labels: Code Improvement, Fix

#2168 Remove Text Macros in strings without interpolated expression
  code/modules/antagonists/clock_cult/mobs/eminence.dm
  code/modules/clothing/suits/wiz_robe.dm
  code/modules/hydroponics/seeds.dm
Labels: Code Improvement

#2160 Fixes a couple things that told me I should pass the override flag
  nsv13/code/modules/munitions/ship_weapons/volatility_component.dm
  nsv13/code/modules/overmap/hull_plating.dm
Labels: Fix, Active Test Merge

#2140 Fixes some duplicate definitions
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pastry.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Code Improvement, Active Test Merge

#2127 Fixes some oversights made in the Bot Multi-Z Movement PR
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/mob/living/simple_animal/bot/mulebot.dm
Labels: Code Improvement, Fix, Active Test Merge

#2158 Fixes Galactica and Rocinante loading errors
  _maps/map_files/Galactica/Galactica1.dmm
  _maps/map_files/Mining/nsv13/Rocinante.dmm
Labels: Active Test Merge, Galactica, Rocinante, mapping

#2135 Snake Atmos Plasma Routing Change
  _maps/map_files/Snake/snake_lower.dmm
  _maps/map_files/Snake/snake_upper.dmm
Labels: Active Test Merge, mapping, Snake

#2172 Executive Officer Stamp
  _maps/map_files/Aetherwhisp/Aetherwhisp2.dmm
  _maps/map_files/Atlas/atlas2.dmm
  _maps/map_files/Galactica/Galactica2.dmm
  _maps/map_files/Shrike/Shrike1.dmm
  _maps/map_files/Snake/snake_lower.dmm
  _maps/map_files/Tycoon/Tycoon1.dmm
  code/modules/asset_cache/asset_list_items.dm
  nsv13/code/modules/paperwork/stamps.dm
  nsv13/icons/obj/bureaucracy.dmi
  nsv13/icons/stamp_icons/large_stamp-xo.png
Labels: Feature, Active Test Merge, mapping

#2123 RCD constructed airlocks will now use NSV icons
  code/game/objects/items/RCD.dm
  nsv13.dme
  nsv13/code/game/objects/items/RCD.dm
Labels: Fix, Active Test Merge

#2103 Adding More Banners
  _maps/map_files/Aetherwhisp/Aetherwhisp2.dmm
  nsv13/code/game/objects/items/religion.dm
  nsv13/icons/mob/inhands/equipment/banners_lefthand.dmi
  nsv13/icons/mob/inhands/equipment/banners_righthand.dmi
  nsv13/icons/obj/banners.dmi
Labels: Sprites, Feature, Needs Review, Active Test Merge, mapping, hacktoberfest-accepted

#2018 Fixes invisible grilles
  nsv13/code/game/turfs/legacy_smooth.dm
Labels: Fix, Active Test Merge, Atlas

#2188 Fixes holokoi error sprite on Galactica
  _maps/map_files/Galactica/Galactica2.dmm
Labels: Fix, mapping

#2163 Fixes some chairs being able to be picked up
  nsv13/code/game/general_quarters/dropship.dm
  nsv13/code/game/objects/structures/mono_sofa.dm
  nsv13/code/game/objects/structures/shuttlecraft_chair.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/gauss_gun.dm
Labels: Fix, Active Test Merge

#2085 Starmap V and a visit from an old friend!
  _maps/aetherwhisp.json
  _maps/atlas.json
  _maps/eclipse.json
  _maps/galactica.json
  _maps/gladius.json
  _maps/hammerhead.dm
  _maps/hammerhead.json
  _maps/map_files/Hammerhead/Hammerhead.dmm
  _maps/shrike.json
  _maps/snake.json
  _maps/tycoon.json
  config/starmap/starmap.svg
  config/starmap/starmap_default.json
  nsv13/code/__DEFINES/overmap.dm
  nsv13/code/controllers/subsystem/starsystem.dm
  nsv13/code/game/gamemodes/pvp/items.dm
  nsv13/code/game/machinery/computer/_ship.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/deck_guns.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/gauss_gun.dm
  nsv13/code/modules/overmap/ai-skynet.dm
  nsv13/code/modules/overmap/traders.dm
  nsv13/code/modules/overmap/traders_items.dm
  nsv13/code/modules/overmap/types/nanotrasen.dm
  nsv13/code/modules/reagents/chemistry/reagents/pyrotechnic_reagents.dm
  nsv13/icons/overmap/new/nanotrasen/heavy_cruiser.dmi
Labels: Sprites, Config Update, Active Test Merge, Hammerhead, mapping, Starsystem, hacktoberfest-accepted

#2171 Reduce Crew Monitor Update Time
  code/game/machinery/computer/crew.dm
Labels: Tweak, Balance/Rebalance, Active Test Merge

#2185 Clothing fix
  code/modules/jobs/job_types/chief_engineer.dm
  code/modules/jobs/job_types/head_of_personnel.dm
  icons/mob/accessories.dmi
Labels: Sprites, Fix, Tweak, Active Test Merge

#2167 Bulk Torpedo/Missile Crates
  nsv13/code/modules/cargo/packs.dm
Labels: Feature, Balance/Rebalance, Active Test Merge, Munitions

#2183 Potentially fixes the monkey-human issue
  code/datums/dna.dm
  code/modules/mob/dead/new_player/new_player.dm
Labels: Fix, Active Test Merge

#2096 Fixes the boarding objective
  nsv13/code/game/gamemodes/overmap/objectives/board_ship.dm
Labels: Fix, Active Test Merge, Passed Test Merge, Starsystem, hacktoberfest-accepted

#2129 Adds Highjack, a new drug for IPC's!
  nsv13.dme
  nsv13/code/modules/reagents/chemistry/reagents/drug_reagents.dm
  nsv13/code/modules/reagents/chemistry/recipes/drugs.dm
Labels: Feature, Active Test Merge

#2166 ZeroG Torp Drag
  nsv13/code/modules/munitions/ammunition/missiles/missile_types.dm
  nsv13/code/modules/munitions/ammunition/torpedos/torpedo_types.dm
  nsv13/code/modules/munitions/ship_weapons/ammunition.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/deck_guns.dm
Labels: Tweak, Active Test Merge, Munitions

#2193 Fixes Atlas distro loop and scrubber loop being together + Adds FLARE to Atlas
  _maps/map_files/Atlas/atlas2.dmm
Labels: Active Test Merge, mapping

#2164 Tweaks astrometrics scans
  nsv13/code/modules/research/astrometrics.dm
Labels: Tweak, Balance/Rebalance, Active Test Merge, Starsystem

#2189 Allows ghosts to double-click into dropship/sabre interiors again
  nsv13/code/modules/overmap/boarding/interiors.dm
Labels: Overmap

#2192 Makes a Named Mulebot gain a new name!
  _maps/map_files/Tycoon/Tycoon2.dmm
Labels: Fix, Active Test Merge, Tycoon, mapping

#2157 Fixes some logout runtimes
  code/datums/elements/weather_listener.dm
  code/datums/hud.dm
Labels: Code Improvement, Fix, Active Test Merge

#2175 Fixes pilots being unable to hear hails
  nsv13/code/modules/overmap/fighters/_fighters.dm
Labels: Active Test Merge, Overmap

#2199 Fixes the Aetherwhisp's torpedo tubes
  nsv13/code/modules/overmap/types/solgov.dm
Labels: Fix, Active Test Merge

#2116 Tweaks ammo sorter repairs and fighter armor repairs
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/revision2/automation.dm
  nsv13/code/modules/overmap/fighters/_fighters.dm
Labels: Tweak, Active Test Merge, Munitions, Fighters
