Repository BeeStation/NSV13, pull requests merged in 2022-07, with the labels that each got.

#1970 Makes it so A and D still steer in inertial mode
  nsv13/code/modules/overmap/overmap.dm
  nsv13/code/modules/overmap/physics.dm
Labels: Fix, Active Test Merge, Passed Test Merge, Overmap

#1959 [READY] Atlas Maintenance
  _maps/map_files/Atlas/atlas.dmm
  _maps/map_files/Atlas/atlas2.dmm
Labels: Active Test Merge, mapping, Atlas

#1797 More Sabre fixes
  _maps/map_files/Gladius/Gladius2.dmm
  _maps/map_files/Instanced/map_files/Babylon1.dmm
  _maps/map_files/Instanced/map_files/SpaceSHIP.dmm
  _maps/map_files/Mining/nsv13/asteroids/asteroid1.dmm
  _maps/map_files/Mining/nsv13/ruins/mining5.dmm
  _maps/templates/boarding/dropship.dmm
  _maps/templates/boarding/dropship_main.dmm
  _maps/templates/boarding/dropship_syndicate.dmm
  _maps/templates/boarding/gunship.dmm
  _maps/templates/boarding/sabre_interior.dmm
  _maps/templates/boarding/sabre_interior_mining.dmm
  _maps/templates/boarding/sabre_interior_syndicate.dmm
  code/__DEFINES/nsv13.dm
  code/_compile_options.dm
  code/controllers/subsystem/explosion.dm
  code/datums/map_config.dm
  code/modules/mapping/space_management/space_reservation.dm
  code/modules/mapping/space_management/space_transition.dm
  code/modules/projectiles/projectile.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/ftl.dm
  nsv13.dme
  nsv13/code/__HELPERS/overmap.dm
  nsv13/code/game/area/areas.dm
  nsv13/code/game/gamemodes/overmap/objectives/cargo/transfer/fighter_parts.dm
  nsv13/code/game/general_quarters/dropship.dm
  nsv13/code/game/general_quarters/dropship_types.dm
  nsv13/code/game/turfs/custom_turfs.dm
  nsv13/code/modules/cargo/packs.dm
  nsv13/code/modules/mob/mob.dm
  nsv13/code/modules/overmap/boarding/interiors.dm
  nsv13/code/modules/overmap/fighters/_fighters.dm
  nsv13/code/modules/overmap/fighters/control_console.dm
  nsv13/code/modules/overmap/fighters/fighters_launcher.dm
  nsv13/code/modules/overmap/fighters/modules/cargo_hold.dm
  nsv13/code/modules/overmap/fighters/modules/ftl_drive.dm
  nsv13/code/modules/overmap/fighters/modules/refueling_kit.dm
  nsv13/code/modules/overmap/fighters/modules/repair_kit.dm
  nsv13/code/modules/overmap/fighters/vv_docking.dm
  nsv13/code/modules/overmap/ftl.dm
  nsv13/code/modules/overmap/overmap.dm
  nsv13/code/modules/overmap/physics.dm
  nsv13/code/modules/research/designs/fighter_designs.dm
  tgui/packages/tgui/interfaces/FighterController.js
  tgui/packages/tgui/interfaces/FighterControls.js
Labels: Fix, Active Test Merge, mapping, TGUI-Changes

#1946 Adding assigned departments to Midshipmen + assigning Munitions department
  code/__DEFINES/preferences.dm
  code/_globalvars/lists/flavor_misc.dm
  code/modules/client/preferences.dm
  code/modules/jobs/job_types/assistant.dm
  icons/mob/accessories.dmi
  icons/obj/clothing/accessories.dmi
  nsv13/code/game/objects/items/munitions_items.dm
  nsv13/code/modules/jobs/job_types/marine/military_police.dm
  nsv13/icons/mob/accessories.dmi
  nsv13/icons/obj/custom_radio.dmi
Labels: Sprites, Feature, Active Test Merge

#1967 Ports Cargo Beret, Quartermaster Turtleneck
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/modules/clothing/under/jobs/cargo.dm
  code/modules/vending/wardrobes.dm
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Sprites, Active Test Merge, Update

#1958 Ports making vended items go into your hands and refactors item giving, table slapping now included!
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/status_effects.dm
  code/_onclick/hud/alert.dm
  code/datums/traits/neutral.dm
  code/game/objects/items.dm
  code/game/objects/items/weaponry.dm
  code/modules/mob/living/carbon/inventory.dm
  code/modules/vending/_vending.dm
Labels: Fix, Tweak, Refactor, Active Test Merge, Update

#1990 Dradis fixes
  nsv13/code/modules/overmap/radar.dm
  nsv13/code/modules/power/stormdrive.dm
  tgui/packages/tgui/interfaces/Dradis.js
Labels: Fix, Active Test Merge, TGUI-Changes

#1981 Ammo sorter features
  nsv13/code/game/machinery/computer/helm.dm
  nsv13/code/game/objects/items/nsv_circuitboards.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/50Cal.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/deck_guns.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/revision2/automation.dm
  nsv13/code/modules/munitions/ship_weapons/energy_weapons/bsa.dm
  nsv13/code/modules/munitions/ship_weapons/hybrid_weapons/hybrid_railgun.dm
  nsv13/code/modules/overmap/armour/nano_pump.dm
  nsv13/code/modules/overmap/radar.dm
  tgui/packages/tgui/interfaces/AmmoSorter.js
Labels: Feature, Fix, Tweak, Active Test Merge, TGUI-Changes, Munitions

#1985 Ports the Species specific mutations from Upstream
  code/__DEFINES/DNA.dm
  code/datums/mutations/actions.dm
  code/datums/mutations/body.dm
  code/datums/mutations/hulk.dm
  code/game/objects/items/dna_injector.dm
  code/modules/mob/living/carbon/human/species_types/ethereal.dm
  code/modules/mob/living/carbon/human/species_types/felinid.dm
  code/modules/mob/living/carbon/human/species_types/mothmen.dm
  code/modules/mob/living/carbon/human/species_types/oozelings.dm
  code/modules/surgery/organs/wings.dm
Labels: Feature, Active Test Merge, Update

#1974 [PORT] Converts ai tracking towards using signals
  code/_onclick/ai.dm
  code/game/machinery/camera/tracking.dm
  code/game/objects/items/devices/multitool.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/death.dm
  code/modules/mob/living/silicon/ai/freelook/eye.dm
Labels: Code Improvement, Active Test Merge, Update

#1969 Adds rule reminders to revivals of various kinds.
  code/game/machinery/cloning.dm
  code/game/objects/items/defib.dm
  code/modules/surgery/advanced/revival.dm
Labels: Feature, Active Test Merge

#1911 Another felinid PR, This one is serious for a change, Adds TG tail sprites
  icons/mob/mutant_bodyparts.dmi
Labels: Sprites, Active Test Merge, horny trash

#1972 Makes chameleon clothing work for NSV clothes
  code/modules/clothing/chameleon.dm
Labels: Fix, Active Test Merge

#1968 Adds more fleets, makes points mission shorter, and a minor fix
  nsv13/code/controllers/subsystem/starsystem.dm
  nsv13/code/game/gamemodes/overmap/objectives/tickets.dm
  nsv13/code/modules/overmap/ai-skynet.dm
  nsv13/code/modules/overmap/factions.dm
Labels: Fix, Starsystem

#1989 Adds cross-server news reports for NSV specific round ends
  code/__DEFINES/misc.dm
  code/controllers/subsystem/ticker.dm
  nsv13/code/modules/overmap/ftl.dm
  nsv13/code/modules/overmap/overmap.dm
Labels: Feature, Active Test Merge

#1991 Lets biosuits hold large internal tanks
  code/modules/clothing/suits/bio.dm
Labels: Feature, Active Test Merge, Update

#2004 Fixes sabres being able to bring all overmap objects into a system
  nsv13/code/modules/overmap/ftl.dm
Labels: Active Test Merge

#2003 Fixes fighter pilots being unable to get out when their canopy is broken
  nsv13/code/modules/overmap/fighters/_fighters.dm
Labels: Active Test Merge

#1993 AI ships no longer shoot at asteroids
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/revision2/vls.dm
Labels: Fix, Active Test Merge, Overmap
