Repository BeeStation/NSV13, pull requests merged in 2022-01, with the labels that each got.

#1771 Hostile Boarders Fix
  nsv13/code/modules/overmap/boarding/boarding.dm
Labels: Fix

#1763 Gives Syndicate crew weapon auth implants
  nsv13/code/game/gamemodes/pvp/roles.dm
Labels: Fix, Active Test Merge

#1768 Makes ammo stackers upgradable via matter bins
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/revision2/automation.dm
Labels: Feature, Balance/Rebalance, Active Test Merge

#1713 KNPC cleanup and optimizations
  nsv13/code/modules/overmap/knpc.dm
Labels: Sprites, Code Improvement

#1753 Beebase fixes - conveyor speed, envirosuits, and more
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/turfs/open/openspace.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/mob/living/simple_animal/bot/atmosbot.dm
  code/modules/recycling/conveyor2.dm
  code/modules/research/designs/comp_board_designs.dm
  code/modules/research/techweb/all_nodes.dm
  nsv13/code/game/objects/items/bridge_items.dm
  nsv13/code/modules/jobs/job_types/marine/marine.dm
  nsv13/code/modules/jobs/job_types/marine/military_police.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/revision2/automation.dm
Labels: Fix, Balance/Rebalance, Active Test Merge

#1759 Attempts to resolve the frankly ungodly amounts of lag currently caused by stuff
  code/controllers/subsystem/air.dm
  code/controllers/subsystem/explosion.dm
  code/game/atoms_movable.dm
  code/game/objects/effects/effect_system/effects_foam.dm
  code/modules/atmospherics/environmental/LINDA_turf_tile.dm
  code/modules/mob/mob.dm
  code/modules/projectiles/projectile.dm
  code/modules/turbolift/turbolift_machines.dm
Labels: Code Improvement, Fix, FUCK, Active Test Merge

#1780 Makes Syndicate bombers visible
  nsv13/code/modules/overmap/types/syndicate.dm
Labels: Fix, Active Test Merge
