Repository BeeStation/NSV13, pull requests merged in 2022-12, with the labels that each got.

#2206 Makes munitions control computers buildable
  nsv13/code/game/objects/items/nsv_circuitboards.dm
  nsv13/code/modules/research/techweb/all_nsv_nodes.dm
Labels: Fix, Tweak

#2023 [Port] Printer TGUI, Printer Forms and Species specific rear printer photos
  code/modules/asset_cache/asset_list_items.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/abductors.dm
  code/modules/mob/living/carbon/human/species_types/felinid.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/species_types/oozelings.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  code/modules/mob/living/carbon/human/species_types/podpeople.dm
  code/modules/paperwork/stamps.dm
  config/blanks.json
  icons/ass/assalien.png
  icons/ass/asscat.png
  icons/ass/assdrone.png
  icons/ass/assfemale.png
  icons/ass/assgrey.png
  icons/ass/asslizard.png
  icons/ass/assmachine.png
  icons/ass/assmale.png
  icons/ass/assplasma.png
  icons/ass/asspodperson.png
  icons/ass/assslime.png
  icons/obj/bureaucracy.dmi
  icons/stamp_icons/large_stamp-void.png
  nsv13.dme
  nsv13/code/modules/paperwork/photocopier.dm
  tgui/packages/tgui/interfaces/Photocopier.js
Labels: Sprites, Config Update, SQL, Active Test Merge, TGUI-Changes

#2030 [PORT] TGUI: Remote Robot Control
  code/modules/mob/living/silicon/ai/ai.dm
  nsv13.dme
  nsv13/code/modules/mob/living/silicon/ai/robot_control.dm
  tgui/packages/tgui/interfaces/RemoteRobotControl.js
Labels: Active Test Merge, TGUI-Changes

#2213 [READY] Fixes asteroid mining - get_overmap() fix and unit tests
  code/modules/client/loadout/loadout.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/get_overmap.dm
  nsv13/code/__HELPERS/overmap.dm
  nsv13/code/game/area/areas.dm
  nsv13/code/modules/overmap/boarding/interiors.dm
Labels: Fix, Active Test Merge, Overmap, mining

#2219 [PORT] Update continuous_integration.yml
  .github/workflows/continuous_integration.yml
Labels: GitHub

#2170 [PORT] Custom say emotes and Emphasis
  code/__DEFINES/logging.dm
  code/__DEFINES/say.dm
  code/__HELPERS/_logging.dm
  code/datums/chatmessage.dm
  code/datums/emotes.dm
  code/game/atoms.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/say.dm
  code/modules/client/verbs/ooc.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm
  code/modules/mob/mob.dm
  code/modules/mob/say.dm
Labels: Feature, Active Test Merge, Update, Port

#2068 The blast shower: an abrasive solution to radioactive contamination
  nsv13.dme
  nsv13/code/game/machinery/blast_shower.dm
  nsv13/icons/obj/blast_shower.dmi
Labels: Feature, Active Test Merge

#2215 Turns overmap vector datums into matrices
  nsv13.dme
  nsv13/code/controllers/subsystem/starsystem.dm
  nsv13/code/modules/collision/collision_helpers.dm
  nsv13/code/modules/collision/collision_response.dm
  nsv13/code/modules/collision/matrixvector.dm
  nsv13/code/modules/collision/shape.dm
  nsv13/code/modules/overmap/ai-skynet.dm
  nsv13/code/modules/overmap/armour/armour_quadrant.dm
  nsv13/code/modules/overmap/fighters/fighters_launcher.dm
  nsv13/code/modules/overmap/fighters/tug.dm
  nsv13/code/modules/overmap/overmap.dm
  nsv13/code/modules/overmap/physics.dm
  nsv13/code/modules/overmap/physics2d.dm
  nsv13/code/modules/projectiles/projectile.dm
Labels: Code Improvement, Refactor, Needs Review, Active Test Merge, Ship/Physics, Overmap

#2197 Nsv13 boarding changes
  _maps/templates/boarding/syndicate/carrier.dmm
  _maps/templates/boarding/syndicate/destroyer.dmm
  _maps/templates/boarding/syndicate/mako.dmm
  _maps/templates/boarding/syndicate/mako_carrier.dmm
  _maps/templates/boarding/syndicate/marine_frigate.dmm
  _maps/templates/boarding/syndicate/nukefrigate.dmm
Labels: Fix, Tweak, Active Test Merge, Mapping

#2220 Makes fastmos work again
  auxtools/auxmos.dll
Labels: Fix, Active Test Merge

#2218 Fixes the Map verb
  interface/interface.dm
Labels: Fix, Active Test Merge

#2217 Fixes missing sprites
  nsv13/code/game/objects/items/custom_guns.dm
  nsv13/code/game/objects/items/custom_items.dm
  nsv13/code/modules/clothing/custom_clothes.dm
  nsv13/code/modules/jobs/security/weapons.dm
  nsv13/icons/mob/inhands/weapons/guns_lefthand.dmi
  nsv13/icons/mob/inhands/weapons/guns_righthand.dmi
Labels: Sprites, Active Test Merge

#2226 NSV13 ModPC Program Cat and Fix
  nsv13/code/modules/power/reactor/rbmk.dm
  nsv13/code/modules/power/stormdrive.dm
  nsv13/code/modules/ship_missions/hail_computer.dm
  nsv13/code/modules/squads/squad_computers.dm
Labels: Fix, Active Test Merge

#2121 [Bounty] Accessing The Wiki through the PDA
  code/game/objects/items/devices/PDA/PDA.dm
Labels: Feature, Active Test Merge

#2203 New traitor item: Point Defence Rifle
  nsv13/code/game/objects/items/custom_guns.dm
  nsv13/code/modules/munitions/ammunition/magazines.dm
  nsv13/code/modules/overmap/weapons/projectiles_fx.dm
  nsv13/code/modules/uplink/uplink_items.dm
  nsv13/icons/mob/inhands/weapons/guns_lefthand.dmi
  nsv13/icons/mob/inhands/weapons/guns_righthand.dmi
  nsv13/icons/obj/guns/projectile.dmi
Labels: Sprites, Feature, Active Test Merge, Mapping

#2162 Post-Beebase Shrike Update
  _maps/map_files/Shrike/Shrike1.dmm
  _maps/map_files/Shrike/Shrike2.dmm
  nsv13.dme
  nsv13/code/game/objects/effects/decals/alt_guideline.dm
  nsv13/code/game/objects/items/storage_items.dm
  nsv13/icons/turf/decals.dmi
Labels: Sprites, Tweak, Balance/Rebalance, Active Test Merge, Mapping, Shrike
