Repository BeeStation/NSV13, pull requests merged in 2022-04, with the labels that each got.

#1854 Kills the asteroid chasm (maybe this time for real)
  code/game/turfs/open/water.dm
Labels: Fix, Active Test Merge

#1875 Fixes being able to use the AGCNR after a meltdown
  nsv13/code/modules/power/reactor/rbmk.dm
Labels: Fix, Active Test Merge

#1872 Fixes Gauss Gun buckle trap
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/gauss_gun.dm
Labels: Fix, Active Test Merge

#1874 random optimizations and code cleaning
  nsv13/code/controllers/subsystem/ranks.dm
  nsv13/code/controllers/subsystem/starsystem.dm
  nsv13/code/modules/mining/asteroid.dm
Labels: Code Improvement, Active Test Merge

#1866 Hungry gunpowder bag
  nsv13.dme
  nsv13/code/datums/components/crafting/recipes.dm
  nsv13/code/modules/jobs/job_types/cook.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/deck_guns.dm
  nsv13/code/modules/munitions/ship_weapons/volatility_component.dm
  nsv13/icons/obj/munitions/deck_gun.dmi
Labels: Feature, Active Test Merge

#1880 Ghosts cannot load guns
  nsv13/code/modules/munitions/ammunition/torpedos/torpedo_types.dm
  nsv13/code/modules/munitions/munitions_trolley.dm
  nsv13/code/modules/munitions/ship_weapons/_ship_weapon.dm
  nsv13/code/modules/munitions/ship_weapons/ammunition.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/deck_guns.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/gauss_gun.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/revision2/automation.dm
Labels: Fix, FUCK, Active Test Merge

#1888 [S] Solves @dependabot's skill issue
  tgui/yarn.lock
Labels: security, TGUI-Changes

#1877 update byond version to 514.1583
  Dockerfile
  code/_compile_options.dm
  code/modules/client/client_procs.dm
  dependencies.sh
Labels: Config Update

#1801 overmap borders are more seamless for AI, and for shooting
  nsv13/code/__HELPERS/overmap.dm
  nsv13/code/modules/overmap/ai-skynet.dm
  nsv13/code/modules/overmap/ai.dm
  nsv13/code/modules/overmap/physics.dm
  nsv13/code/modules/overmap/radar.dm
Labels: Fix, Balance/Rebalance, VIBE CHECK, Active Test Merge, Overmap

#1846 Fixes some bad reference stuff with player ships
  nsv13/code/game/machinery/computer/helm.dm
  nsv13/code/game/machinery/computer/tactical.dm
  nsv13/code/modules/munitions/ship_weapons/_ship_weapon.dm
  nsv13/code/modules/overmap/weapons/ship_weapon.dm
Labels: Code Improvement, Active Test Merge

#1869 Knpc node next_id supports lists
  nsv13/code/modules/overmap/knpc.dm
Labels: Feature, Active Test Merge, Roadmap

#1876 Fixes Ammo Rack Control Console UI
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/revision2/automation.dm
Labels: Fix, Active Test Merge

#1887 Ensmallens the starmap
  config/starmap/starmap_default.json
  nsv13/code/controllers/subsystem/starsystem.dm
Labels: Config Update, Active Test Merge, Starsystem

#1890 Glock ammo crates give 5 mags instead of 1
  nsv13/code/modules/cargo/packs.dm
Labels: Tweak, Active Test Merge

#1895 Removed Unknown Elevator Button on The Tycoon
  _maps/map_files/Tycoon/Tycoon1.dmm
Labels: Active Test Merge, Tycoon, mapping
