Repository BeeStation/NSV13, pull requests merged in 2022-03, with the labels that each got.

#1790 Fashionable Bomber jacket accessory
  icons/mob/accessories.dmi
  nsv13/code/game/machinery/munitions_machinery.dm
  nsv13/code/modules/clothing/custom_clothes.dm
  nsv13/icons/obj/clothing/accessories.dmi
Labels: Sprites, Active Test Merge

#1844 Moves the Atlas ladder, you know the one
  _maps/map_files/Atlas/atlas.dmm
  _maps/map_files/Atlas/atlas2.dmm
Labels: mapping, Atlas

#1856 DNA console upstream fix
  code/game/machinery/computer/dna_console.dm
Labels: Fix

#1793 Bloody Eye (Again, I'm sorry)
  nsv13.dme
  nsv13/code/game/objects/items/bloody_eye.dm
  nsv13/icons/obj/nsv13_syringe.dmi
Labels: Feature, Active Test Merge

#1719 Adds dynamic starmap loading (resolve #1716)
  code/__DEFINES/flags.dm
  code/__DEFINES/nsv13.dm
  code/__DEFINES/subsystems.dm
  code/_globalvars/bitfields.dm
  code/controllers/configuration/entries/game_options.dm
  code/datums/map_config.dm
  config/game_options.txt
  config/starmap/README.md
  config/starmap/starmap_default.json
  nsv13/code/controllers/subsystem/starsystem.dm
  nsv13/code/game/gamemodes/pvp/items.dm
  nsv13/code/modules/overmap/ai-skynet.dm
  nsv13/code/modules/overmap/effects.dm
  nsv13/code/modules/overmap/ftl.dm
  nsv13/icons/obj/munitions_large.dmi
  tgui/packages/tgui/styles/components/Map.scss
Labels: enhancement, Feature, Config Update, FUCK, Refactor, VIBE CHECK, Active Test Merge, TGUI-Changes, Starsystem

#1867 [s] Ports Topic Security Issue Fix
  code/game/world.dm
Labels: Fix, security

#1868 Timeline Correction - 2263 -> 2262 edition
  code/__DEFINES/nsv13.dm
Labels: Fix

#1857 fix #1849
  nsv13/code/modules/overmap/ai-skynet.dm
Labels: Fix, Active Test Merge

#1853 AI ships no longer try to predict shots when using hitscan weapons
  nsv13/code/modules/overmap/physics.dm
Labels: Code Improvement, Active Test Merge, Overmap

#1781 Proof of Concept: Ghost Ships
  code/__DEFINES/role_preferences.dm
  code/_globalvars/lists/poll_ignore.dm
  code/modules/admin/admin_verbs.dm
  nsv13.dme
  nsv13/code/controllers/subsystem/overmap_mode.dm
  nsv13/code/controllers/subsystem/starsystem.dm
  nsv13/code/datums/weapon_types.dm
  nsv13/code/game/general_quarters/dropship.dm
  nsv13/code/game/general_quarters/dropship_types.dm
  nsv13/code/game/machinery/computer/_ship.dm
  nsv13/code/game/machinery/computer/salvage.dm
  nsv13/code/game/machinery/computer/tactical.dm
  nsv13/code/modules/munitions/ammunition/countermeasure_ammo.dm
  nsv13/code/modules/overmap/ai-skynet.dm
  nsv13/code/modules/overmap/boarding/boarding.dm
  nsv13/code/modules/overmap/camera.dm
  nsv13/code/modules/overmap/fighters/_fighters.dm
  nsv13/code/modules/overmap/overmap.dm
  nsv13/code/modules/overmap/overmap_ghosts.dm
  nsv13/code/modules/overmap/verbs.dm
  nsv13/code/modules/overmap/weapons/weapons.dm
  tgui/packages/tgui/interfaces/GhostTacticalConsole.js
  tgui/packages/tgui/interfaces/OvermapGamemodeController.js
Labels: enhancement, Code Improvement, Administration, Balance/Rebalance, Refactor, Active Test Merge, TGUI-Changes, Overmap, Experimental Test Candidate
