Repository BeeStation/NSV13, pull requests merged in 2022-09, with the labels that each got.

#2008 Torp (and volatility component fixes, again, this time for real)
  code/game/objects/obj_defense.dm
  nsv13/code/modules/munitions/ammunition/torpedos/torpedo_parts.dm
  nsv13/code/modules/munitions/ammunition/torpedos/torpedo_types.dm
  nsv13/code/modules/munitions/ship_weapons/ammunition.dm
  nsv13/code/modules/munitions/ship_weapons/volatility_component.dm
  nsv13/code/modules/overmap/fighters/_fighters.dm
  nsv13/code/modules/overmap/overmap.dm
  nsv13/code/modules/overmap/physics.dm
  nsv13/code/modules/overmap/weapons/damage.dm
  nsv13/code/modules/overmap/weapons/projectiles_fx.dm
  nsv13/code/modules/research/designs/munitions_designs.dm
  nsv13/code/modules/research/techweb/all_nsv_nodes.dm
  nsv13/icons/obj/munition_types.dmi
  nsv13/icons/obj/munitions.dmi
Labels: Feature, Fix, Balance/Rebalance, Active Test Merge, Overmap, Munitions

#2040 Makes the 10 count torp crates actually include 10 of the listed component
  nsv13/code/modules/cargo/packs.dm
Labels: Fix, Active Test Merge

#2043 AIs can now hear fleet hails
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Fix, Active Test Merge, Overmap

#2033 Glass Tiles and Reinforced version now have a material var so they can be recycled
  nsv13/code/game/objects/items/stacks/tiles/tile_types.dm
Labels: Fix, Active Test Merge

#2034 Adds Ration Packs to Sustenance Vendors
  code/modules/vending/sustenance.dm
Labels: Feature, Active Test Merge

#2025 Fixes invisible bullets for Glocks and pulse rifles
  nsv13/code/game/objects/items/custom_guns.dm
  nsv13/code/modules/jobs/security/weapons.dm
Labels: Fix, Active Test Merge

#2048 Replaced string overmap roles with bitflags
  code/__DEFINES/nsv13.dm
  code/_globalvars/bitfields.dm
  nsv13/code/datums/weapon_types.dm
  nsv13/code/game/machinery/computer/_ship.dm
  nsv13/code/game/machinery/computer/helm.dm
  nsv13/code/game/machinery/computer/tactical.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/50Cal.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/revision2/vls.dm
  nsv13/code/modules/munitions/ship_weapons/energy_weapons/laser_ams.dm
  nsv13/code/modules/overmap/camera.dm
  nsv13/code/modules/overmap/fighters/_fighters.dm
  nsv13/code/modules/overmap/overmap.dm
  nsv13/code/modules/overmap/overmap_ghosts.dm
  nsv13/code/modules/overmap/weapons/damage.dm
  nsv13/code/modules/overmap/weapons/ship_weapon.dm
  nsv13/code/modules/overmap/weapons/weapons.dm
Labels: Code Improvement, Overmap

#2022 Adds selling boarder gear for cash with cargo
  nsv13.dme
  nsv13/code/modules/cargo/exports/syndie.dm
Labels: Feature, Balance/Rebalance, Active Test Merge

#2024 New glocks for security
  code/modules/jobs/job_types/warden.dm
  nsv13/code/modules/jobs/job_types/marine/military_police.dm
  nsv13/code/modules/jobs/security/weapons.dm
  nsv13/icons/obj/guns/projectile.dmi
Labels: Sprites, Feature, Balance/Rebalance, Active Test Merge

#1966 Beg mappers to talk to maintainers
  .github/CONTRIBUTING.md
Labels: GitHub

#2039 Emotional Support Torpedo
  nsv13/code/datums/components/crafting/recipes.dm
  nsv13/code/datums/mood_events/nsv_events.dm
  nsv13/code/modules/munitions/ammunition/torpedos/torpedo_parts.dm
  nsv13/code/modules/munitions/ammunition/torpedos/torpedo_types.dm
  nsv13/code/modules/overmap/weapons/projectiles_fx.dm
  nsv13/icons/obj/munition_types.dmi
Labels: Sprites, Feature, Active Test Merge, Munitions

#2072 Fixes fighter fueling at any distance
  nsv13/code/modules/overmap/fighters/fuel_tank.dm
Labels: Fix, Active Test Merge, Fighters

#2069 Stormdrive overload numbers tweak
  nsv13/code/modules/power/stormdrive.dm
Labels: Tweak, Active Test Merge
