Repository BeeStation/NSV13, pull requests merged in 2022-02, with the labels that each got.

#1711 Significant physics subsystem optimizations
  code/__DEFINES/subsystems.dm
  code/controllers/subsystem/processing/projectiles.dm
  nsv13.dme
  nsv13/code/game/atoms_movable.dm
  nsv13/code/modules/collision/shape.dm
  nsv13/code/modules/collision/vector2d.dm
  nsv13/code/modules/overmap/ai-skynet.dm
  nsv13/code/modules/overmap/ai.dm
  nsv13/code/modules/overmap/overmap.dm
  nsv13/code/modules/overmap/physics.dm
  nsv13/code/modules/overmap/physics2d.dm
  nsv13/code/modules/projectiles/projectile.dm
Labels: Refactor, Active Test Merge, Ship/Physics

#1798 Ports paper fix from BeeStation
  tgui/packages/tgui/interfaces/PaperSheet.js
Labels: Fix, TGUI-Changes

#1802 Fixes material fuel rods.
  nsv13/code/modules/power/reactor/fuel_rods.dm
  nsv13/icons/obj/control_rod.dmi
Labels: Sprites, Fix, Active Test Merge

#1791 Adds a new admin smite
  code/__DEFINES/admin.dm
  code/modules/admin/verbs/randomverbs.dm
  nsv13/code/modules/munitions/munitions_trolley.dm
  nsv13/code/modules/munitions/ship_weapons/ammunition.dm
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/deck_guns.dm
  nsv13/code/modules/overmap/weapons/projectiles_fx.dm
Labels: Feature, Administration, Active Test Merge

#1794 Tweaks overmap interior explosions on destruction
  nsv13/code/modules/overmap/ai_interiors.dm
Labels: Tweak, Active Test Merge

#1816 Fixes missile casings disassembly
  nsv13/code/modules/munitions/ammunition/missiles/missile_construction.dm
Labels: Fix, Active Test Merge

#1795 Ports background subsystem fix
  code/controllers/subsystem.dm
Labels: Code Improvement, Fix, Active Test Merge

#1762 Munitions Machinery Maintenance Mechanics: Ammo Stackers/Sorters
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/revision2/automation.dm
  nsv13/sound/effects/ship/mac_load_jam.ogg
  nsv13/sound/effects/ship/mac_load_unjam.ogg
Labels: Feature, Balance/Rebalance, Active Test Merge

#1818 Makes the gas monitor UI shorter
  tgui/packages/tgui/interfaces/AtmosControlConsole.js
Labels: Fix, Active Test Merge, TGUI-Changes

#1817 IFF and Hammerlock tweaks
  nsv13/code/game/machinery/computer/salvage.dm
  nsv13/code/game/machinery/iff_console.dm
  nsv13/code/modules/overmap/ai-skynet.dm
  nsv13/code/modules/overmap/types/solgov.dm
Labels: Tweak, Balance/Rebalance, Active Test Merge

#1831 Removes shaft miner bubblegum objective
  code/modules/crew_objectives/cargo_objectives.dm
Labels: Fix, Active Test Merge

#1832 Adds space law to book management consoles and SecTech
  code/modules/library/lib_machines.dm
  code/modules/vending/security.dm
Labels: Feature, Active Test Merge

#1800 Atlas Maintenance pass
  _maps/atlas.json
  _maps/map_files/Atlas/atlas.dmm
  _maps/map_files/Atlas/atlas2.dmm
  nsv13/code/game/area/areas.dm
Labels: mapping, Atlas

#1772 Boardable Carriers 2
  _maps/templates/boarding/syndicate/carrier.dmm
  nsv13/code/modules/overmap/types/syndicate.dm
Labels: mapping

#1812 Shrike Mining Update
  _maps/map_files/Shrike/Shrike1.dmm
  _maps/map_files/Shrike/Shrike2.dmm
  _maps/shrike.json
Labels: Active Test Merge, mapping, Shrike

#1841 Removes unidentified type path that I didn't notice during review
  _maps/templates/boarding/syndicate/carrier.dmm
Labels: mapping

#1828 pilots can't shoot while incapacitated now
  nsv13/code/modules/overmap/fighters/_fighters.dm
Labels: Fix, Active Test Merge

#1826 Makes advanced tools yellow in-hand
  icons/mob/inhands/equipment/tools_lefthand.dmi
  icons/mob/inhands/equipment/tools_righthand.dmi
  icons/obj/tools.dmi
Labels: Sprites, Fix, Active Test Merge

#1822 Fixes round not ending on dynamic
  code/game/gamemodes/dynamic/dynamic.dm
Labels: Active Test Merge
