Repository BeeStation/NSV13, pull requests merged in 2023-07, with the labels that each got.

#2424 Fixes midshipman department assignments
  nsv13/code/modules/jobs/job_types/marine/midshipman.dm
Labels: Fix, Active Test Merge

#2441 Adds mentor-themed pranks
  _maps/map_files/Instanced/elcoPT.json
  _maps/map_files/Instanced/map_files/NSVElcoPT.dmm
  nsv13.dme
  nsv13/code/game/gamemodes/pvp/roles.dm
  nsv13/code/modules/clothing/custom_clothes.dm
  nsv13/code/modules/clothing/custom_outfits.dm
  nsv13/code/modules/mob/living/carbon/human/species_types/catgirl.dm
  nsv13/code/modules/overmap/boarding/boarding.dm
  nsv13/code/modules/overmap/knpc.dm
  nsv13/code/modules/overmap/types/syndicate.dm
  nsv13/icons/mob/accessories.dmi
  nsv13/icons/mob/hands.dmi
  nsv13/icons/mob/head.dmi
  nsv13/icons/mob/suit.dmi
  nsv13/icons/mob/uniform.dmi
  nsv13/icons/obj/clothing/accessories.dmi
  nsv13/icons/obj/clothing/gloves.dmi
  nsv13/icons/obj/clothing/hats.dmi
  nsv13/icons/obj/clothing/uniforms.dmi
  nsv13/icons/overmap/new/syndicate/pt_boat.dmi
Labels: Feature, Fix, Active Test Merge, Mapping

#2443 Makes it easier to identify what charge you are on as an Ethereal
  code/_onclick/hud/alert.dm
  code/modules/mob/living/carbon/human/species_types/ethereal.dm
  icons/mob/screen_alert.dmi
Labels: Sprites, Feature, Active Test Merge, Port

#2446 Fixes a few things on Atlas
  _maps/map_files/Atlas/atlas.dmm
  _maps/map_files/Atlas/atlas2.dmm
Labels: Fix, Active Test Merge, Mapping, Atlas

#2448 Showers no longer are useless for contamination above 0 but below 18
  code/game/objects/structures/shower.dm
Labels: Balance/Rebalance, Active Test Merge

#2475 [PORT] Adds custom rubber mag sprite #9405
  code/modules/projectiles/boxes_magazines/external/smg.dm
  icons/obj/ammo.dmi
Labels: Sprites, Update

#2489 [Upstream] Fixes duplicate small crack on carpet examine
  code/game/turfs/open/floor/fancy_floor.dm
Labels: Fix, Update

#2274 [PORT] Flavor Roleplaying Overhaul
  SQL/beestation_schema.sql
  code/datums/datacore.dm
  code/datums/dna.dm
  code/game/machinery/computer/medical.dm
  code/game/machinery/computer/security.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences2/character_save.dm
  code/modules/client/preferences2/preferences2.dm
  code/modules/client/verbs/looc.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/dummy.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/silicon/examine.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/mob.dm
  nsv13.dme
  nsv13/code/modules/mob/living/carbon/examine_tgui.dm
  tgui/packages/tgui/components/Box.tsx
  tgui/packages/tgui/interfaces/ExaminePanel.js
Labels: Feature, Code Improvement, Fix, SQL, Refactor, Active Test Merge, TGUI-Changes

#2427 [PORT] Cargo and Cyborg Munitions Upgrade
  code/__DEFINES/robots.dm
  code/game/objects/items/stacks/wrap.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/paperwork/clipboard.dm
  code/modules/research/techweb/all_nodes.dm
  icons/mob/robots.dmi
  icons/mob/screen_cyborg.dmi
  nsv13.dme
  nsv13/code/__DEFINES/robot_defines.dm
  nsv13/code/modules/mob/living/silicon/robot/cargoborg_items.dm
  nsv13/code/modules/mob/living/silicon/robot/muni_upgrade.dm
  nsv13/code/modules/mob/living/silicon/robot/robot_modules.dm
  nsv13/code/modules/mob/living/silicon/robot/update_icons.dm
  nsv13/code/modules/research/designs/mechfabricator_designs.dm
  nsv13/code/modules/research/techweb/all_nsv_nodes.dm
  nsv13/icons/mob/silicon/robots_cargo.dmi
  sound/mecha/hydraulic.ogg
Labels: Sprites, Feature, Balance/Rebalance, Sound, Refactor, Active Test Merge, Munitions, Port

#2445 Fixes holomap dels
  code/datums/components/holomap.dm
  code/modules/mob/dead/observer/login.dm
Labels: Fix, Active Test Merge, Update

#2447 AMS shot counter
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/revision2/vls.dm
  nsv13/code/modules/overmap/overmap.dm
  nsv13/code/modules/overmap/weapons/weapons.dm
  tgui/packages/tgui/interfaces/AMS.js
Labels: Feature, Active Test Merge, TGUI-Changes, Munitions

#2453 [PORT] Gives foxes a walking animation
  icons/mob/pets.dmi
Labels: Sprites, Active Test Merge, Port

#2459 Personal Armor Bullet/Laser rebalance
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/clothing/suits/armor.dm
Labels: Balance/Rebalance, Active Test Merge

#2467 Fixes squad manager download and run permissions
  nsv13/code/modules/squads/squad_computers.dm
Labels: Fix, Active Test Merge, Squads

#2469 Tycoon Request Consoles and Stormdrive Fix
  _maps/map_files/Tycoon/Tycoon1.dmm
  _maps/map_files/Tycoon/Tycoon2.dmm
Labels: Fix, Active Test Merge, Tycoon, Mapping

#2472 Coffee typo fix
  nsv13/code/modules/coffee/items/coffee_pack.dm
Labels: Fix, Active Test Merge

#2466 Makes latejoins wake up from cryostasis instead of arriving on a shuttle
  _maps/atlas.json
  _maps/map_files/Aetherwhisp/Aetherwhisp1.dmm
  _maps/map_files/Atlas/atlas2.dmm
  _maps/map_files/Eclipse/Eclipse1.dmm
  _maps/map_files/Galactica/Galactica1.dmm
  _maps/map_files/Galactica/Galactica2.dmm
  _maps/map_files/Gladius/Gladius2.dmm
  _maps/map_files/Hammerhead/Hammerhead.dmm
  _maps/map_files/Serendipity/Serendipity1.dmm
  _maps/map_files/Shrike/Shrike2.dmm
  _maps/map_files/Snake/snake_lower.dmm
  _maps/map_files/Tycoon/Tycoon2.dmm
  _maps/map_files/Vago/vagodeck1.dmm
  _maps/map_files/Vago/vagodeck2.dmm
  _maps/serendipity.json
  nsv13/code/datums/shuttles.dm
Labels: Removal, Active Test Merge, Low Priority, Mass Map Change, Mapping
