Repository BeeStation/NSV13, pull requests merged in 2023-11, with the labels that each got.

#2545 Makes windows have damage overlays - Fixes #675
  nsv13/code/game/turfs/legacy_smooth.dm
Labels: Fix, Active Test Merge

#2568 Fixes Snake ammo sorters and integrity failsafe
  _maps/map_files/Snake/snake_lower.dmm
  nsv13/code/modules/overmap/types/nanotrasen.dm
Labels: Fix, Active Test Merge, Mapping, Snake

#2565 Adds a familiar fighter sprite as a colorizer
  nsv13.dme
  nsv13/code/game/objects/items/colorizers/fighters.dm
  nsv13/code/modules/client/loadout/loadout_colorizers.dm
Labels: Active Test Merge, Fighters

#2561 Porting Smite to dock pay
  code/__DEFINES/admin.dm
  code/modules/admin/verbs/randomverbs.dm
Labels: Feature, Administration, Active Test Merge

#2562 Fixes a runtime in the power generation crew objective
  nsv13/code/modules/crew_objectives/engineering_objectives.dm
Labels: Fix, Active Test Merge

#2544 [Upstream] Update to Python 3.11.2, Node 18.14.2, Inferno 8, Typescript 4.9, Yarn 3.4
  .github/workflows/compile_changelogs.yml
  .github/workflows/continuous_integration.yml
  .github/workflows/make_changelogs.yml
  dependencies.sh
  tgui/.eslintrc-sonar.yml
  tgui/.eslintrc.yml
  tgui/.yarn/releases/yarn-3.1.1.cjs
  tgui/.yarn/releases/yarn-3.4.1.cjs
  tgui/.yarn/sdks/eslint/bin/eslint.js
  tgui/.yarn/sdks/eslint/lib/api.js
  tgui/.yarn/sdks/eslint/package.json
  tgui/.yarn/sdks/typescript/bin/tsc
  tgui/.yarn/sdks/typescript/bin/tsserver
  tgui/.yarn/sdks/typescript/lib/tsc.js
  tgui/.yarn/sdks/typescript/lib/tsserver.js
  tgui/.yarn/sdks/typescript/lib/tsserverlibrary.js
  tgui/.yarn/sdks/typescript/lib/typescript.js
  tgui/.yarn/sdks/typescript/package.json
  tgui/.yarnrc.yml
  tgui/package.json
  tgui/packages/tgfont/package.json
  tgui/packages/tgui-bench/package.json
  tgui/packages/tgui-dev-server/package.json
  tgui/packages/tgui-panel/package.json
  tgui/packages/tgui-polyfill/package.json
  tgui/packages/tgui/components/Box.tsx
  tgui/packages/tgui/components/LabeledList.tsx
  tgui/packages/tgui/components/Popper.tsx
  tgui/packages/tgui/components/Section.tsx
  tgui/packages/tgui/components/Tooltip.tsx
  tgui/packages/tgui/interfaces/Astrometrics.js
  tgui/packages/tgui/interfaces/NtosLogViewer.js
  tgui/packages/tgui/interfaces/Stack.js
  tgui/packages/tgui/interfaces/SurgeryInitiator.tsx
  tgui/packages/tgui/package.json
  tgui/tsconfig.json
  tgui/yarn.lock
  tools/bootstrap/python311._pth
  tools/bootstrap/python_.ps1
  tools/changelog/requirements.txt
  tools/requirements.txt
Labels: tools, GitHub, Active Test Merge, TGUI-Changes

#2555 Plated Catwalk Fixes, And Construction
  code/_onclick/click.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/door.dm
  code/game/objects/structures/catwalk.dm
  code/game/turfs/open/floor/plating.dm
  code/game/turfs/turf.dm
  nsv13/code/game/objects/items/stacks/tiles/tile_types.dm
  nsv13/code/game/objects/structures/catwalk.dm
  nsv13/icons/obj/smooth_structures/catwalk_plated.dmi
Labels: Sprites, Feature, Fix, Active Test Merge

#2575 Lets ghost ships use gauss
  nsv13/code/modules/overmap/overmap_ghosts.dm
Labels: Feature, Active Test Merge, Overmap

#2577 Update TGS DMAPI
  code/__DEFINES/tgs.dm
  code/modules/tgs/core/_definitions.dm
  code/modules/tgs/core/core.dm
  code/modules/tgs/core/datum.dm
  code/modules/tgs/v3210/commands.dm
  code/modules/tgs/v4/api.dm
  code/modules/tgs/v4/commands.dm
  code/modules/tgs/v5/__interop_version.dm
  code/modules/tgs/v5/_defines.dm
  code/modules/tgs/v5/api.dm
  code/modules/tgs/v5/commands.dm
  code/modules/tgs/v5/serializers.dm
  code/modules/tgs/v5/topic.dm
  code/modules/tgs/v5/undefs.dm
Labels: invalid, Active Test Merge, Update

#2576 Coffee machines for all Galactic Conquest maps & Syndicate coffee mood
  _maps/map_files/Instanced/map_files/Babylon2.dmm
  _maps/map_files/Instanced/map_files/Hammurabi1.dmm
  _maps/map_files/Instanced/map_files/SpaceSHIP.dmm
  nsv13/code/datums/mood_events/nsv_events.dm
  nsv13/code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Fix, Active Test Merge, Mapping, Astraeus, Babylon, Hammurabi

#2558 NSV Materials Fix
  nsv13/code/game/objects/items/custom_materials.dm
  nsv13/code/game/objects/items/stacks/tiles/tile_types.dm
  nsv13/code/modules/research/designs/smelting_designs.dm
Labels: Fix, Balance/Rebalance, Active Test Merge

#2571 Syndicate bomb plushie traitor item
  nsv13/code/game/objects/items/nsv13_plushes.dm
  nsv13/code/game/objects/items/storage_items.dm
  nsv13/code/modules/uplink/uplink_items.dm
  nsv13/icons/obj/custom_plushes.dmi
Labels: Sprites, Feature, Active Test Merge
