Repository BeeStation/NSV13, pull requests merged in 2023-02, with the labels that each got.

#2299 Messages mentioning the Delphic Expanse replaced with Rosetta Cluster
  nsv13/code/controllers/subsystem/overmap_mode.dm
  nsv13/code/game/gamemodes/overmap/courier.dm
  nsv13/code/game/gamemodes/overmap/shakedown.dm
  nsv13/code/modules/Security/genpop.dm
Labels: Fix, Active Test Merge

#2227 Adds multiz trunks to pipe dispensers
  code/game/objects/items/RPD.dm
  icons/obj/atmospherics/pipes/disposal.dmi
Labels: Sprites, Feature, Multi-Z, Active Test Merge, Pending Upstream Port

#2248 Attempts to patch the issue the bots currently have where they randomly get stuck
  code/modules/mob/living/simple_animal/bot/bot.dm
  nsv13/code/modules/mob/living/simple_animal/bot/catmed.dm
Labels: Fix, Do Not Merge, Multi-Z, Active Test Merge

#1999 Boarder refactor
  nsv13/code/modules/overmap/boarding/boarding.dm
  nsv13/code/modules/overmap/knpc.dm
Labels: documentation, Feature, Active Test Merge

#2287 Allows uncharted systems to be used as fleet spawns
  nsv13/code/modules/overmap/factions.dm
Labels: Fix, Active Test Merge, Starsystem

#2296 [PORT] Fixes Cameras by giving them all planes.
  code/_onclick/hud/plane_master.dm
  code/game/machinery/computer/camera.dm
  code/game/turfs/open/openspace.dm
  code/game/turfs/turf.dm
Labels: Fix, Active Test Merge, Update

#2289 [Upstream] Fluffy Insect Expansion Pack
  code/__DEFINES/DNA.dm
  code/__DEFINES/status_effects.dm
  code/__HELPERS/global_lists.dm
  code/__HELPERS/mobs.dm
  code/_globalvars/lists/flavor_misc.dm
  code/datums/diseases/advance/symptoms/clockwork.dm
  code/modules/admin/create_mob.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences2/character_save.dm
  code/modules/mob/dead/new_player/sprite_accessories.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/mothmen.dm
  code/modules/surgery/bodyparts/bodyparts.dm
  code/modules/surgery/organs/wings.dm
  icons/mob/moth_antennae.dmi
  icons/mob/moth_markings.dmi
  icons/mob/moth_wings.dmi
  icons/mob/moth_wingsopen.dmi
Labels: Sprites, Feature, Fix, Tweak, Administration, Update, horny trash

#2291 Adds proper handling to VLS tube exiting
  nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/revision2/vls.dm
Labels: Fix, Active Test Merge

#2300 Adds teleporter beacons to the Galactica
  _maps/map_files/Galactica/Galactica1.dmm
  _maps/map_files/Galactica/Galactica2.dmm
Labels: Galactica, Mapping

#2210 makes all food forkable
  code/game/objects/items/kitchen.dm
  code/modules/food_and_drinks/food/snacks.dm
  icons/obj/kitchen.dmi
Labels: Sprites, Feature, Tweak, Pending Upstream Port

#2313 Fixes crates with missing names
  nsv13/code/modules/cargo/packs.dm
Labels: Fix, Active Test Merge

#2314 Gives Winona much needed buffs
  _maps/map_files/Eclipse/Eclipse1.dmm
  code/game/gamemodes/objective_items.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/projectiles/gun.dm
  nsv13/code/modules/jobs/security/weapons.dm
Labels: Balance/Rebalance, Active Test Merge, Mapping, Eclipse

#2315 Adds brakes to tugs
  code/__DEFINES/nsv13.dm
  code/datums/keybinding/_defines.dm
  nsv13.dme
  nsv13/code/datums/keybinding/vehicle.dm
  nsv13/code/modules/vehicles/_vehicle.dm
Labels: Feature, Code Improvement, Needs Test Merge
