Repository BeeStation/NSV13, pull requests merged in 2023-08, with the labels that each got.

#2494 Fixes Prisoner Console not giving brief
  nsv13/code/modules/Security/genpop.dm
Labels: Fix

#2458 Cargo Voidfill
  code/modules/cargo/packs.dm
  nsv13/code/modules/cargo/packs.dm
  nsv13/code/modules/jobs/security/weapons.dm
Labels: Feature, Balance/Rebalance, Active Test Merge, I dead please restart

#2503 Prevents other fleets from shooting boarding objective targets
  nsv13/code/game/gamemodes/overmap/objectives/board_ship.dm
Labels: Fix, Active Test Merge, Overmap, boarding

#2491 Fixes SolGov sending taunt hails to allied ships
  nsv13/code/modules/overmap/ai-skynet.dm
Labels: Fix, Active Test Merge

#2490 Trader station UI set to autoupdate
  nsv13/code/modules/overmap/traders.dm
Labels: UI, Tweak, Active Test Merge

#2486 Snake disposal fixes, Adds conquest beacon
  _maps/map_files/Snake/snake_lower.dmm
Labels: Fix, Active Test Merge, Mapping, Snake

#2482 Replaces wardens energy gun
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/jobs/job_types/warden.dm
Labels: Balance/Rebalance, Active Test Merge

#2480 Fixes related to syndicate maid clothes and accessories, adds the syndicate maid kit as a 20 TC uplink item
  code/modules/clothing/under/_under.dm
  icons/mob/accessories.dmi
  nsv13/code/game/objects/items/storage_items.dm
  nsv13/code/modules/clothing/custom_clothes.dm
  nsv13/code/modules/uplink/uplink_items.dm
  nsv13/icons/mob/accessories.dmi
  nsv13/icons/obj/clothing/accessories.dmi
Labels: Sprites, Feature, Fix, Active Test Merge

#2495 Felinid ears buff
  code/modules/surgery/organs/ears.dm
Labels: Balance/Rebalance, Active Test Merge

#2478 Fixes the "Prisoner Management Console" circuitboard
  code/game/objects/items/circuitboards/computer_circuitboards.dm
  code/modules/research/designs/comp_board_designs.dm
Labels: Fix, Active Test Merge

#2474 [Modular] Coffee Addictions
  nsv13/code/datums/traits/negative.dm
  nsv13/code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Feature, Active Test Merge

#2461 Fix the HomeOne
  _maps/map_files/Instanced/map_files/HomeOne.dmm
Labels: Fix, Active Test Merge, Mapping

#2387 Hammerhead Atmos and Hangar Rebuild
  _maps/map_files/Hammerhead/Hammerhead.dmm
  code/game/machinery/airlock_cycle_control.dm
  nsv13/code/modules/overmap/fighters/_fighters.dm
  nsv13/code/modules/overmap/overmap.dm
Labels: Active Test Merge, Hammerhead, Mapping

#2286 Aetherwhisp Touchups
  _maps/map_files/Aetherwhisp/Aetherwhisp1.dmm
  _maps/map_files/Aetherwhisp/Aetherwhisp2.dmm
Labels: Active Test Merge, Aetherwisp, Mapping

#2473 Adds the black skirt and maid outfit to the torp shop
  code/game/objects/items/storage/boxes.dm
  nsv13.dme
  nsv13/code/game/objects/items/storage_items.dm
  nsv13/code/modules/client/loadout/loadout_general.dm
  nsv13/code/modules/client/loadout/loadout_uniform.dm
Labels: Feature, Active Test Merge, horny trash

#2499 Makes MP16 not obsolete
  nsv13/code/game/objects/items/custom_guns.dm
  nsv13/icons/mob/inhands/weapons/guns_lefthand.dmi
  nsv13/icons/mob/inhands/weapons/guns_righthand.dmi
Labels: Sprites, Balance/Rebalance, Active Test Merge

#2501 Secborg loadout update
  code/modules/mob/living/silicon/robot/robot_modules.dm
  config/game_options.txt
  nsv13/code/modules/jobs/security/weapons.dm
  nsv13/icons/obj/guns/projectile.dmi
Labels: Feature, Config Update, Balance/Rebalance, Active Test Merge

#2498 Atlas Atmospherics Rebuild
  _maps/map_files/Atlas/atlas.dmm
  _maps/map_files/Atlas/atlas2.dmm
Labels: Tweak, Active Test Merge, Mapping, Atlas

#2512 simplemobs can no longer drive tugs (1984)
  code/modules/vehicles/sealed.dm
Labels: Fix, Active Test Merge

#2511 APNW slider can be set to zero now
  nsv13/code/modules/overmap/armour/nano_well.dm
Labels: Fix, Active Test Merge

#2484 [PORT] Navbeacon Refactor
  _maps/map_files/Aetherwhisp/Aetherwhisp1.dmm
  _maps/map_files/Aetherwhisp/Aetherwhisp2.dmm
  _maps/map_files/Atlas/atlas.dmm
  _maps/map_files/Atlas/atlas2.dmm
  _maps/map_files/Galactica/Galactica1.dmm
  _maps/map_files/Galactica/Galactica2.dmm
  _maps/map_files/Snake/snake_lower.dmm
  _maps/map_files/Snake/snake_upper.dmm
  _maps/map_files/Tycoon/Tycoon2.dmm
  code/__DEFINES/radio.dm
  code/__DEFINES/robots.dm
  code/game/machinery/navbeacon.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/mob/living/simple_animal/bot/mulebot.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/shuttle/on_move.dm
  nsv13/code/game/objects/items/nsv_circuitboards.dm
  nsv13/code/modules/research/designs/nsv_circuitboard_designs.dm
  tgui/packages/tgui/interfaces/NavBeacon.tsx
Labels: Fix, Active Test Merge, Mass Map Change, Mapping, TGUI-Changes, Port

#2493 Overmap Ship normal damage type immunity
  nsv13/code/__DEFINES/overmap.dm
  nsv13/code/modules/overmap/overmap.dm
Labels: Tweak, Active Test Merge, Overmap

#2509 Fixes plasma constrictors not rotating and misc additions
  nsv13.dme
  nsv13/code/modules/atmospherics/machinery/components/binary_devices/constrictor.dm
  nsv13/code/modules/power/stormdrive.dm
Labels: Feature, Code Improvement, Fix, Tweak, Active Test Merge

#2510 attempts a fix to the overlapping borg crew manifest hud
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/robot.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/modular_computers/file_system/programs/borg_self_monitor.dm
  icons/mob/screen_cyborg.dmi
  nsv13/code/modules/overmap/armour/nano_well.dm
  tgui/packages/tgui/interfaces/NtosCyborgSelfMonitor.js
Labels: Sprites, Fix, Active Test Merge, TGUI-Changes

#2514 Fixes torpedo crate coming with missile warheads
  nsv13/code/modules/cargo/packs.dm
Labels: Fix, Active Test Merge

#2515 Fixes a problem with guns
  code/modules/projectiles/gun.dm
Labels: Fix, Active Test Merge

#2523 Holomap fix + AI gets one too
  code/datums/components/holomap.dm
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Fix, Tweak, Active Test Merge

#2481 9mm ammo types to protolathe
  code/modules/research/techweb/all_nodes.dm
  icons/obj/ammo.dmi
  nsv13/code/modules/jobs/security/weapons.dm
Labels: Sprites, Feature, Balance/Rebalance, Active Test Merge
