Repository BeeStation/NSV13, pull requests merged in 2023-12, with the labels that each got.

#2411 Updates client versions
  code/controllers/configuration/entries/general.dm
  code/modules/client/client_procs.dm
  config/config.txt
Labels: Config Update, Active Test Merge, Port

#2574 Some munitions accessories
  nsv13.dme
  nsv13/code/modules/mob/dead/new_player/sprite_accessories.dm
  nsv13/icons/mob/underwear.dmi
Labels: Sprites, Feature, Active Test Merge

#2591 'Ports' PR labeler fix from Beestation
  .github/workflows/extra_pr_labels.yml
Labels: Fix, GitHub, Update

#2573 Adds special offers to overmap traders
  nsv13/code/modules/overmap/traders.dm
  nsv13/code/modules/overmap/traders_items.dm
Labels: Balance/Rebalance, Active Test Merge, Munitions, Starsystem

#2582 Species names are colored when examining / health analyzing
  code/game/objects/items/devices/scanners.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/species_types/ethereal.dm
  nsv13.dme
  nsv13/code/modules/mob/living/carbon/human/nsv_human_helpers.dm
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
Labels: Feature, Fix, Active Test Merge, TGUI-Changes, Port

#2586 Fixes FTL pylons getting stuck in the shutdown state
  nsv13/code/modules/overmap/FTL/components/drive.dm
  nsv13/code/modules/overmap/FTL/components/drive_pylon.dm
Labels: Fix, Active Test Merge

#2587 Syndicate (AI) boarding has a tell again
  nsv13/code/modules/overmap/boarding/boarding.dm
Labels: Fix, Active Test Merge
