Repository BeeStation/NSV13, pull requests merged in 2024-08, with the labels that each got.

#2652 Added a cross-server comms cooldown failure message
  code/game/machinery/computer/communications.dm
Labels: Tweak, Active Test Merge

#2673 fix auto recall warnings not made during combat
  nsv13/code/controllers/subsystem/overmap_mode.dm
Labels: Fix, Active Test Merge

#2636 Replaces generic HOS spacesuit with nerfed Mjolnir
  _maps/map_files/Aetherwhisp/Aetherwhisp1.dmm
  _maps/map_files/Atlas/atlas2.dmm
  _maps/map_files/Galactica/Galactica1.dmm
  _maps/map_files/Galactica/old/Galactica_old.dmm
  _maps/map_files/Gladius/Gladius1.dmm
  _maps/map_files/Hammerhead/Hammerhead.dmm
  _maps/map_files/Serendipity/Serendipity1.dmm
  _maps/map_files/Shrike/Shrike1.dmm
  _maps/map_files/Snake/snake_upper.dmm
  _maps/map_files/Tycoon/Tycoon2.dmm
  _maps/map_files/Vago/vagodeck1.dmm
  code/modules/clothing/spacesuits/hardsuit.dm
  nsv13/code/modules/clothing/custom_clothes.dm
  nsv13/icons/mob/head.dmi
  nsv13/icons/mob/suit.dmi
  nsv13/icons/obj/clothing/hats.dmi
  nsv13/icons/obj/clothing/suits.dmi
Labels: Feature, Balance/Rebalance, Active Test Merge, Mass Map Change, Mapping

#2694 Fixes jaws of life airlock interactions & tiny bit of beebase cleanup
  code/game/machinery/doors/airlock.dm
Labels: Code Improvement, Fix, Active Test Merge

#2696 Allows you to choose which direction you lay down towards
  code/modules/mob/living/living.dm
Labels: Feature, Active Test Merge

#2700 Adds Ore Silo to Atlas
  _maps/map_files/Atlas/atlas2.dmm
Labels: Active Test Merge, Mapping, Atlas

#2695 Fixes broadside cannon direction recognition
  nsv13/code/__HELPERS/misc.dm
Labels: Fix, Active Test Merge

#2691 Adds random ore turfs to, and updates, existing mining ruins.
  _maps/map_files/Mining/nsv13/ruins/mining10.dmm
  _maps/map_files/Mining/nsv13/ruins/mining11.dmm
  _maps/map_files/Mining/nsv13/ruins/mining12.dmm
  _maps/map_files/Mining/nsv13/ruins/mining13.dmm
  _maps/map_files/Mining/nsv13/ruins/mining14.dmm
  _maps/map_files/Mining/nsv13/ruins/mining15.dmm
  _maps/map_files/Mining/nsv13/ruins/mining16.dmm
  _maps/map_files/Mining/nsv13/ruins/mining17.dmm
  _maps/map_files/Mining/nsv13/ruins/mining18.dmm
  _maps/map_files/Mining/nsv13/ruins/mining19.dmm
  _maps/map_files/Mining/nsv13/ruins/mining20.dmm
  _maps/map_files/Mining/nsv13/ruins/mining21.dmm
  _maps/map_files/Mining/nsv13/ruins/mining22.dmm
  _maps/map_files/Mining/nsv13/ruins/mining23.dmm
  _maps/map_files/Mining/nsv13/ruins/mining24.dmm
  _maps/map_files/Mining/nsv13/ruins/mining25.dmm
  _maps/map_files/Mining/nsv13/ruins/mining26.dmm
  _maps/map_files/Mining/nsv13/ruins/mining27.dmm
  _maps/map_files/Mining/nsv13/ruins/mining28.dmm
  _maps/map_files/Mining/nsv13/ruins/mining29.dmm
  _maps/map_files/Mining/nsv13/ruins/mining5.dmm
  _maps/map_files/Mining/nsv13/ruins/mining6.dmm
  _maps/map_files/Mining/nsv13/ruins/mining7.dmm
  _maps/map_files/Mining/nsv13/ruins/mining8.dmm
  _maps/map_files/Mining/nsv13/ruins/mining9.dmm
Labels: Active Test Merge, Mapping, mining

#2697 Fixes the "You are Dead" tgui window popup
  code/modules/mob/dead/observer/logout.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/login.dm
  code/modules/mob/mob.dm
Labels: Fix, Active Test Merge
