Repository BeeStation/NSV13, pull requests merged in 2024-04, with the labels that each got.

#2606 Enables FTL auto-spool mode on the Thirring FTL drive
  nsv13/code/modules/overmap/FTL/components/drive.dm
Labels: Fix, Balance/Rebalance, Active Test Merge

#2617 Imports prosthetics from paradise(mostly)
  code/game/machinery/aug_manipulator.dm
  nsv13/icons/mob/augmentation/bishop.dmi
  nsv13/icons/mob/augmentation/shellguard.dmi
  nsv13/icons/mob/augmentation/veymed.dmi
  nsv13/icons/mob/augmentation/veymedm.dmi
  nsv13/icons/mob/augmentation/wardtakahashi.dmi
  nsv13/icons/mob/augmentation/xion.dmi
  nsv13/icons/mob/augmentation/zenghu.dmi
Labels: Sprites, Active Test Merge

#2623 Updates the webmap link
  _maps/aetherwhisp.json
  _maps/atlas.json
  _maps/eclipse.json
  _maps/galactica.json
  _maps/gladius.json
  _maps/hammerhead.json
  _maps/serendipity.json
  _maps/shrike.json
  _maps/snake.json
  _maps/tycoon.json
  _maps/vago.json
  interface/interface.dm
Labels: Active Test Merge, Update, Mapping
