Repository BeeStation/NSV13, pull requests merged in 2024-09, with the labels that each got.

#2666 Sabre insanity, also known as one proc adjustment that might possibly fix stuff (now includes ~300% more proc adjustments)
  nsv13/code/controllers/subsystem/starsystem.dm
  nsv13/code/modules/overmap/FTL/ftl_jump.dm
  nsv13/code/modules/overmap/fighters/fighters_launcher.dm
  nsv13/code/modules/overmap/overmap.dm
  nsv13/code/modules/overmap/weapons/plasma_gun.dm
Labels: Fix, Active Test Merge, Overmap, Fighters

#2699 Makes asteroids not just replace every turf when generating ores
  nsv13/code/modules/mining/asteroid.dm
Labels: Tweak, Active Test Merge, mining

#2685 Stormdrive Gas Update V2.1
  nsv13/code/modules/power/stormdrive.dm
Labels: Feature, Balance/Rebalance, Active Test Merge

#2684 [Semi-Experimental] The coldbloodening
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/life.dm
  nsv13.dme
  nsv13/code/__DEFINES/atmospherics.dm
  nsv13/code/datums/mood_events/nsv_events.dm
  nsv13/code/modules/mob/living/carbon/human/human.dm
  nsv13/code/modules/mob/living/carbon/human/nsv_species.dm
  nsv13/code/modules/mob/living/carbon/human/species_types/nsv_lizardpeople.dm
  nsv13/code/modules/mob/living/nsv_life.dm
Labels: Fix, Balance/Rebalance, Active Test Merge

#2702 More Pylon fixes
  nsv13/code/datums/looping_sounds/_looping_sound.dm
  nsv13/code/modules/overmap/FTL/components/drive.dm
  nsv13/code/modules/overmap/FTL/components/drive_pylon.dm
Labels: Fix, Active Test Merge

#2693 Space mines, Syndicate stealth attacks
  nsv13.dme
  nsv13/code/controllers/subsystem/starsystem.dm
  nsv13/code/modules/overmap/ai-skynet.dm
  nsv13/code/modules/overmap/ai_interiors.dm
  nsv13/code/modules/overmap/armour/armour_quadrant.dm
  nsv13/code/modules/overmap/physics.dm
  nsv13/code/modules/overmap/types/syndicate.dm
  nsv13/code/modules/overmap/weapons/damage.dm
  nsv13/code/modules/overmap/weapons/mines.dm
  nsv13/icons/obj/munition_types.dmi
  nsv13/icons/overmap/effects.dmi
Labels: Feature, Active Test Merge, Overmap, Starsystem

#2667 MAA Hardsuit Sprite Update
  nsv13/code/modules/clothing/custom_clothes.dm
  nsv13/icons/mob/head.dmi
  nsv13/icons/mob/suit.dmi
  nsv13/icons/obj/clothing/hats.dmi
  nsv13/icons/obj/clothing/suits.dmi
Labels: Sprites, Balance/Rebalance, Active Test Merge
