Repository BeeStation/NSV13, pull requests merged in 2025-01, with the labels that each got.

#2733 Hangar Armory Tweaks Hammerhead
  _maps/map_files/Hammerhead/Hammerhead.dmm
Labels: Active Test Merge, Hammerhead, Mapping

#2732 Allows midshipmen that are not assigned to important departments to be in squads.
  nsv13/code/modules/jobs/job_types/marine/midshipman.dm
  nsv13/code/modules/squads/squad_datum.dm
Labels: Tweak, Active Test Merge

#2715 [Port] Hardsuit Tails
  code/modules/mob/dead/new_player/sprite_accessories.dm
  code/modules/mob/living/carbon/human/species.dm
  nsv13.dme
  nsv13/code/modules/clothing/suits/hardsuit_tails.dm
  nsv13/icons/obj/clothing/suits/tails_hardsuit.dmi
Labels: Sprites, Feature, Active Test Merge, Port

#2736 Filter/Mixer Mapping Icon Fixes
  code/modules/atmospherics/machinery/components/trinary_devices/filter.dm
  code/modules/atmospherics/machinery/components/trinary_devices/mixer.dm
Labels: Fix, Active Test Merge, Mapping

#2734 Hammerhead, ram ahead
  nsv13/code/__DEFINES/overmap.dm
  nsv13/code/modules/overmap/fighters/fighters_launcher.dm
  nsv13/code/modules/overmap/overmap.dm
  nsv13/code/modules/overmap/physics.dm
  nsv13/code/modules/overmap/types/nanotrasen.dm
  nsv13/code/modules/overmap/types/syndicate.dm
Labels: Code Improvement, Fix, Balance/Rebalance, Active Test Merge, Overmap

#2735 Adds the ability for elite fleets to spawn at higher difficulties + new elite submarine variant
  nsv13/code/modules/overmap/ai-skynet.dm
  nsv13/code/modules/overmap/factions.dm
  nsv13/code/modules/overmap/types/syndicate.dm
  nsv13/icons/overmap/new/syndicate/cruiser.dmi
Labels: Feature, Balance/Rebalance, Active Test Merge
