Repository BeeStation/NSV13, pull requests merged in 2025-03, with the labels that each got.

#2751 Lets space vines climb ladders and staircases
  code/modules/events/spacevine.dm
Labels: Balance/Rebalance, Active Test Merge

#2745 Adds fullscreen mode to the game
  code/__DEFINES/keybinding.dm
  code/__DEFINES/preferences.dm
  code/__byond_version_compat.dm
  code/datums/keybinding/client.dm
  code/modules/client/preferences.dm
  nsv13.dme
  nsv13/code/modules/client/fullscreen.dm
Labels: Feature, Active Test Merge, Update

#2778 Update github actions cache
  .github/workflows/continuous_integration.yml
Labels: GitHub

#2753 Hammurabi Slightly De-cursed
  _maps/map_files/Instanced/map_files/Hammurabi1.dmm
  _maps/map_files/Instanced/map_files/Hammurabi2.dmm
Labels: Fix, Tweak, Active Test Merge, Mapping, Hammurabi

#2757 B-B-Babylon touchups
  _maps/map_files/Instanced/map_files/Babylon2.dmm
Labels: Tweak, Active Test Merge, Mapping, Babylon

#2758 Delta alert level cannot be manually switched out of.
  code/game/machinery/computer/communications.dm
  code/modules/security_levels/keycard_authentication.dm
Labels: Fix, FRELL, Active Test Merge

#2722 Emergency Jumps
  code/__DEFINES/nsv13.dm
  code/modules/security_levels/keycard_authentication.dm
  nsv13.dme
  nsv13/code/__DEFINES/overmap.dm
  nsv13/code/modules/overmap/FTL/components/drive.dm
  nsv13/code/modules/overmap/FTL/ftl_jump.dm
  nsv13/code/modules/overmap/FTL/ftl_jump_mishaps/jump_mishap_helpers.dm
  nsv13/code/modules/overmap/FTL/ftl_jump_mishaps/phase_ghost.dm
  nsv13/code/modules/overmap/FTL/ftl_legacy.dm
  nsv13/code/modules/overmap/ai-skynet.dm
  nsv13/code/modules/overmap/fighters/_fighters.dm
  nsv13/code/modules/overmap/interdiction.dm
  nsv13/code/modules/overmap/overmap.dm
  nsv13/code/modules/overmap/starmap.dm
  nsv13/code/modules/overmap/weapons/damage.dm
  nsv13/sound/effects/ship/misjump/misjump_exit_01.ogg
  nsv13/sound/effects/ship/misjump/misjump_exit_02.ogg
  nsv13/sound/misc/triple_boop_alert.ogg
  tgui/packages/tgui/interfaces/FTLComputer.js
  tgui/packages/tgui/interfaces/FTLComputerModular.js
  tgui/packages/tgui/interfaces/KeycardAuth.js
  tgui/packages/tgui/interfaces/Starmap.js
Labels: Feature, Fix, Balance/Rebalance, Active Test Merge, TGUI, TGUI-Changes, Overmap

#2761 Snake Area Mapping fix
  _maps/map_files/Snake/snake_lower.dmm
  _maps/map_files/Snake/snake_upper.dmm
Labels: Fix, Active Test Merge, Mapping, Snake

#2784 Fixes helmet cameras not being installed
  nsv13/code/modules/clothing/helmet_camera.dm
Labels: Fix, Active Test Merge

#2779 Fix flap and aflap emotes
  code/modules/mob/living/emote.dm
Labels: Fix, Active Test Merge

#2781 [UPSTREAM] Examining atmos machinery now displays what layer it's on.
  code/modules/atmospherics/machinery/components/components_base.dm
  code/modules/atmospherics/machinery/pipes/pipes.dm
Labels: Feature, Active Test Merge, Update

#2765 Tycoon Update Series- Cargo
  _maps/map_files/Tycoon/Tycoon1.dmm
  _maps/map_files/Tycoon/Tycoon2.dmm
Labels: Active Test Merge, Tycoon, Mapping

#2768 Dipity Mapping Fixes
  _maps/map_files/Serendipity/Serendipity1.dmm
  _maps/map_files/Serendipity/Serendipity2.dmm
  code/modules/power/tesla/coil.dm
  nsv13/code/modules/overmap/weapons/plasma_gun.dm
  nsv13/icons/obj/machinery/tesla_coil.dmi
Labels: Sprites, Fix, Active Test Merge, Mapping, Serendipity

#2769 Fighter components can be alt-clicked to unload its contents
  nsv13/code/modules/overmap/fighters/_fighters.dm
Labels: Fix, Active Test Merge

#2771 Minor firing logic fix
  nsv13/code/modules/overmap/ai-skynet.dm
Labels: Fix, Active Test Merge

#2773 Removes the ghost living in the cryo tubes
  code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
Labels: Fix, Active Test Merge
